[package]
name = "symcrust"
version = "0.1.0"
edition = "2021"
# build = "build.rs"

[dependencies]
libc = "0.2"
itertools = "0.14.0"

[lib]
# Adding lib for the sake of enabling benchmarks, apparently criterion won't
# run against just staticlib
crate-type = ["staticlib", "lib"]

[profile.dev]
panic="abort"

[profile.release]
lto = true
codegen-units = 1
debug = true
panic="abort"

[dev-dependencies]
rand = { version = "0.9.1" }
criterion = { version = "0.5", features = ["html_reports"] }
hex = "0.4.3"
assert_hex = "0.4.1"
ghash = "0.5.1"

[build-dependencies]
pkg-config = "0.3"

[[bench]]
name = "ntt"
harness = false

[features]
benchmarking = ["std"]
std = []
