[package]
name = "symcrust"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"

[lib]
# Adding lib for the sake of enabling benchmarks, apparently criterion won't
# run against just staticlib
crate-type = ["staticlib", "lib"]

[profile.dev]
panic="abort"

[profile.release]
lto = true
codegen-units = 1
debug = true
panic="abort"

[dev-dependencies]
rand = { version = "0.9.1" }
criterion = { version = "0.5", features = ["html_reports"] }
hex = "0.4.3"
assert_hex = "0.4.1"
ghash = "0.5.1"

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "aes"
harness = false

[[bench]]
name = "sha3"
harness = false

[features]
benchmarking = ["std"]
std = []
kernel = []

# Algorithms
# aes = []
# ml-kem = []