-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Symcrust.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open symcrust

/-- [symcrust::common::cpu_features_present]:
    Source: 'src/common.rs', lines 108:0-113:1
    Visibility: public -/
axiom common.cpu_features_present : Std.U32 → Result Bool

/-- [symcrust::common::random]:
    Source: 'src/common.rs', lines 126:0-128:1 -/
axiom common.random : Slice Std.U8 → Result (common.Error × (Slice Std.U8))

/-- [symcrust::common::wipe_slice]:
    Source: 'src/common.rs', lines 136:0-138:1
    Visibility: public -/
axiom common.wipe_slice {T : Type} : Slice T → Result (Slice T)

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::new_in_place]:
    Source: 'src/common.rs', lines 162:4-170:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.new_in_place
  {T : Type} :
  Slice T → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → Slice T))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::new_disjoint]:
    Source: 'src/common.rs', lines 174:4-181:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.new_disjoint
  {T : Type} {N : Std.Usize} :
  Array T N → Array T N → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → Array T N))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::new_disjoint_from_slices]:
    Source: 'src/common.rs', lines 187:4-195:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.new_disjoint_from_slices
  {T : Type} :
  Slice T → Slice T → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → Slice T))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::len]:
    Source: 'src/common.rs', lines 217:4-219:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.len
  {T : Type} : common.InPlaceOrDisjointBuffer T → Result Std.Usize

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::loadu_si128_src]:
    Source: 'src/common.rs', lines 233:4-236:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.loadu_si128_src
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Std.Usize → Result
    core.core_arch.x86.__m128i

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::loadu_si128_dst]:
    Source: 'src/common.rs', lines 256:4-259:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.loadu_si128_dst
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Std.Usize → Result
    core.core_arch.x86.__m128i

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::storeu_si128]:
    Source: 'src/common.rs', lines 274:4-277:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.storeu_si128
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Std.Usize → core.core_arch.x86.__m128i
    → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → common.InPlaceOrDisjointBuffer T))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::src]:
    Source: 'src/common.rs', lines 281:4-283:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.src
  {T : Type} : common.InPlaceOrDisjointBuffer T → Result (Slice T)

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::dst]:
    Source: 'src/common.rs', lines 287:4-289:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.dst
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Result ((Slice T) × (Slice T →
    common.InPlaceOrDisjointBuffer T) × (common.InPlaceOrDisjointBuffer T →
    common.InPlaceOrDisjointBuffer T))

/-- [symcrust::common::try_new_box_zeroed]:
    Source: 'src/common.rs', lines 322:0-327:1
    Visibility: public -/
axiom common.try_new_box_zeroed
  (T : Type) : Result (core.result.Result T common.Error)

/-- [symcrust::common::try_new_box_default]:
    Source: 'src/common.rs', lines 336:0-342:1
    Visibility: public -/
axiom common.try_new_box_default
  {T : Type} (BoxDefaultInst : common.BoxDefault T) :
  Result (core.result.Result T common.Error)

/-- [symcrust::common::const_time_slices_equal_impl]:
    Source: 'src/common.rs', lines 369:0-386:1 -/
axiom common.const_time_slices_equal_impl
  : Slice Std.U8 → Slice Std.U8 → Result Bool

/-- [symcrust::common::const_time_slice_copy_impl]:
    Source: 'src/common.rs', lines 418:0-440:1 -/
axiom common.const_time_slice_copy_impl
  : Slice Std.U8 → Slice Std.U8 → Std.U32 → Result (Slice Std.U8)

/-- [symcrust::mlkem::key::{impl symcrust::common::BoxDefault for symcrust::mlkem::key::Key}::box_default]:
    Source: 'src/mlkem/key.rs', lines 223:4-229:5
    Visibility: public -/
axiom mlkem.key.Key.Insts.SymcrustCommonBoxDefault.box_default
  : MutRawPtr mlkem.key.Key → Result Unit

/-- [symcrust::mlkem::SymCryptMlKemSelftest]:
    Source: 'src/mlkem/mlkem.rs', lines 272:4-272:31 -/
axiom mlkem.SymCryptMlKemSelftest : Result Unit

/-- [symcrust::mlkem::{impl symcrust::common::BoxDefault for symcrust::mlkem::DecapsulateTemps}::box_default]:
    Source: 'src/mlkem/mlkem.rs', lines 777:4-779:5
    Visibility: public -/
axiom mlkem.DecapsulateTemps.Insts.SymcrustCommonBoxDefault.box_default
  : MutRawPtr mlkem.DecapsulateTemps → Result Unit

/-- [symcrust::sha3::keccak4x::{impl core::ops::drop::Drop for symcrust::sha3::keccak4x::Keccak4x}::drop]:
    Source: 'src/sha3/keccak4x.rs', lines 100:4-106:5
    Visibility: public -/
axiom sha3.keccak4x.Keccak4x.Insts.CoreOpsDropDrop.drop
  : sha3.keccak4x.Keccak4x → Result sha3.keccak4x.Keccak4x

/-- [symcrust::sha3::keccak4x_hybrid::load_lane]:
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 158:0-160:1 -/
axiom sha3.keccak4x_hybrid.load_lane
  : sha3.keccak4x_hybrid.Lane4 → Result (Array Std.U8 32#usize)

/-- [symcrust::sha3::keccak4x_hybrid::store_lane]:
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 165:0-167:1 -/
axiom sha3.keccak4x_hybrid.store_lane
  :
  sha3.keccak4x_hybrid.Lane4 → Array Std.U8 32#usize → Result
    sha3.keccak4x_hybrid.Lane4

/-- [symcrust::sha3::keccak4x_hybrid::{impl core::ops::drop::Drop for symcrust::sha3::keccak4x_hybrid::Keccak4xHybrid}::drop]:
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 210:4-216:5
    Visibility: public -/
axiom sha3.keccak4x_hybrid.Keccak4xHybrid.Insts.CoreOpsDropDrop.drop
  :
  sha3.keccak4x_hybrid.Keccak4xHybrid → Result
    sha3.keccak4x_hybrid.Keccak4xHybrid

/-- [symcrust::verify::intrinsics::aes::subbytes_shiftrows]:
    Source: 'src/verify/intrinsics/aes.rs', lines 40:0-43:1
    Visibility: public -/
axiom verify.intrinsics.aes.subbytes_shiftrows
  : Array Std.U8 16#usize → Result (Array Std.U8 16#usize)

/-- [symcrust::verify::intrinsics::aes::inv_subbytes_shiftrows]:
    Source: 'src/verify/intrinsics/aes.rs', lines 67:0-70:1
    Visibility: public -/
axiom verify.intrinsics.aes.inv_subbytes_shiftrows
  : Array Std.U8 16#usize → Result (Array Std.U8 16#usize)

/-- [symcrust::verify::intrinsics::aes::mc]:
    Source: 'src/verify/intrinsics/aes.rs', lines 51:0-54:1
    Visibility: public -/
axiom verify.intrinsics.aes.mc
  : Array Std.U8 16#usize → Result (Array Std.U8 16#usize)

/-- [symcrust::verify::intrinsics::aes::imc]:
    Source: 'src/verify/intrinsics/aes.rs', lines 26:0-29:1
    Visibility: public -/
axiom verify.intrinsics.aes.imc
  : Array Std.U8 16#usize → Result (Array Std.U8 16#usize)

/-- [symcrust::verify::intrinsics::x86_64::pclmulqdq::clmulepi64_si128]:
    Source: 'src/verify/intrinsics/x86_64/pclmulqdq.rs', lines 73:0-76:1
    Visibility: public -/
axiom verify.intrinsics.x86_64.pclmulqdq.clmulepi64_si128
  :
  Array Std.U64 2#usize → Array Std.U64 2#usize → Std.U8 → Result (Array
    Std.U64 2#usize)

/-- [symcrust::verify::intrinsics::x86_64::aes::aesenc_si128]:
    Source: 'src/verify/intrinsics/x86_64/aes.rs', lines 262:0-265:1
    Visibility: public -/
axiom verify.intrinsics.x86_64.aes.aesenc_si128
  :
  Array Std.U8 16#usize → Array Std.U8 16#usize → Result (Array Std.U8
    16#usize)

/-- [symcrust::verify::intrinsics::x86_64::aes::aesdec_si128]:
    Source: 'src/verify/intrinsics/x86_64/aes.rs', lines 283:0-286:1
    Visibility: public -/
axiom verify.intrinsics.x86_64.aes.aesdec_si128
  :
  Array Std.U8 16#usize → Array Std.U8 16#usize → Result (Array Std.U8
    16#usize)

/-- [symcrust::verify::intrinsics::x86_64::aes::aesdeclast_si128]:
    Source: 'src/verify/intrinsics/x86_64/aes.rs', lines 292:0-295:1
    Visibility: public -/
axiom verify.intrinsics.x86_64.aes.aesdeclast_si128
  :
  Array Std.U8 16#usize → Array Std.U8 16#usize → Result (Array Std.U8
    16#usize)

/-- [symcrust::verify::intrinsics::x86_64::sha::sha256rnds2_epu32]:
    Source: 'src/verify/intrinsics/x86_64/sha.rs', lines 150:0-153:1 -/
axiom verify.intrinsics.x86_64.sha.sha256rnds2_epu32
  :
  Array Std.U32 4#usize → Array Std.U32 4#usize → Array Std.U32 4#usize →
    Result (Array Std.U32 4#usize)

/-- [symcrust::verify::intrinsics::x86_64::sha::sha256msg1_epu32]:
    Source: 'src/verify/intrinsics/x86_64/sha.rs', lines 178:0-181:1 -/
axiom verify.intrinsics.x86_64.sha.sha256msg1_epu32
  :
  Array Std.U32 4#usize → Array Std.U32 4#usize → Result (Array Std.U32
    4#usize)

/-- [symcrust::verify::intrinsics::x86_64::sha::sha256msg2_epu32]:
    Source: 'src/verify/intrinsics/x86_64/sha.rs', lines 210:0-213:1 -/
axiom verify.intrinsics.x86_64.sha.sha256msg2_epu32
  :
  Array Std.U32 4#usize → Array Std.U32 4#usize → Result (Array Std.U32
    4#usize)
