-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Symcrust.Code.Types

import Intrinsics.Axioms.Aes
import Intrinsics.Axioms.Aarch64.Aes
import Intrinsics.Axioms.Aarch64.Neon
import Intrinsics.Axioms.X86_64.Aes
import Intrinsics.Axioms.X86_64.Pclmulqdq
import Intrinsics.Axioms.X86_64.Common
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open symcrust

/-- [symcrust::common::try_new_box_zeroed]:
    Source: 'src/common.rs', lines 322:0-327:1
    Visibility: public -/
axiom common.try_new_box_zeroed
  (T : Type) : Result (core.result.Result T common.Error)

/-- [symcrust::common::try_new_box_default]:
    Source: 'src/common.rs', lines 336:0-342:1
    Visibility: public -/
axiom common.try_new_box_default
  {T : Type} (BoxDefaultInst : common.BoxDefault T) :
  Result (core.result.Result T common.Error)

/-- [symcrust::common::cpu_features_present]:
    Source: 'src/common.rs', lines 108:0-113:1
    Visibility: public -/
axiom common.cpu_features_present : Std.U32 → Result Bool

/-- [symcrust::common::random]:
    Source: 'src/common.rs', lines 126:0-128:1 -/
axiom common.random : Slice Std.U8 → Result (common.Error × (Slice Std.U8))

/-- [symcrust::common::wipe_slice]:
    Source: 'src/common.rs', lines 136:0-138:1
    Visibility: public -/
axiom common.wipe_slice {T : Type} : Slice T → Result (Slice T)

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::new_in_place]:
    Source: 'src/common.rs', lines 162:4-170:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.new_in_place
  {T : Type} :
  Slice T → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → Slice T))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::new_disjoint]:
    Source: 'src/common.rs', lines 174:4-181:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.new_disjoint
  {T : Type} {N : Std.Usize} :
  Array T N → Array T N → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → Array T N))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::new_disjoint_from_slices]:
    Source: 'src/common.rs', lines 187:4-195:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.new_disjoint_from_slices
  {T : Type} :
  Slice T → Slice T → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → Slice T))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::len]:
    Source: 'src/common.rs', lines 217:4-219:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.len
  {T : Type} : common.InPlaceOrDisjointBuffer T → Result Std.Usize

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::loadu_si128_src]:
    Source: 'src/common.rs', lines 233:4-236:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.loadu_si128_src
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Std.Usize → Result
    core.core_arch.x86.__m128i

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::loadu_si128_dst]:
    Source: 'src/common.rs', lines 256:4-259:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.loadu_si128_dst
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Std.Usize → Result
    core.core_arch.x86.__m128i

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::storeu_si128]:
    Source: 'src/common.rs', lines 274:4-277:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.storeu_si128
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Std.Usize → core.core_arch.x86.__m128i
    → Result ((common.InPlaceOrDisjointBuffer T) ×
    (common.InPlaceOrDisjointBuffer T → common.InPlaceOrDisjointBuffer T))

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::src]:
    Source: 'src/common.rs', lines 281:4-283:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.src
  {T : Type} : common.InPlaceOrDisjointBuffer T → Result (Slice T)

/-- [symcrust::common::{symcrust::common::InPlaceOrDisjointBuffer<'a, T>}::dst]:
    Source: 'src/common.rs', lines 287:4-289:5
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer.dst
  {T : Type} :
  common.InPlaceOrDisjointBuffer T → Result ((Slice T) × (Slice T →
    common.InPlaceOrDisjointBuffer T) × (common.InPlaceOrDisjointBuffer T →
    common.InPlaceOrDisjointBuffer T))

/-- [symcrust::common::const_time_slices_equal_impl]:
    Source: 'src/common.rs', lines 361:0-378:1 -/
axiom common.const_time_slices_equal_impl
  : Slice Std.U8 → Slice Std.U8 → Result Bool

/-- [symcrust::common::const_time_slice_copy_impl]:
    Source: 'src/common.rs', lines 405:0-427:1 -/
axiom common.const_time_slice_copy_impl
  : Slice Std.U8 → Slice Std.U8 → Std.U32 → Result (Slice Std.U8)

/-- [symcrust::mlkem::key::{impl symcrust::common::BoxDefault for symcrust::mlkem::key::Key}::box_default]:
    Source: 'src/mlkem/key.rs', lines 223:4-229:5
    Visibility: public -/
axiom mlkem.key.Key.Insts.SymcrustCommonBoxDefault.box_default
  : MutRawPtr mlkem.key.Key → Result Unit

/-- [symcrust::mlkem::SymCryptMlKemSelftest]:
    Source: 'src/mlkem/mlkem.rs', lines 266:4-266:31 -/
axiom mlkem.SymCryptMlKemSelftest : Result Unit

/-- [symcrust::mlkem::{impl symcrust::common::BoxDefault for symcrust::mlkem::DecapsulateTemps}::box_default]:
    Source: 'src/mlkem/mlkem.rs', lines 771:4-773:5
    Visibility: public -/
axiom mlkem.DecapsulateTemps.Insts.SymcrustCommonBoxDefault.box_default
  : MutRawPtr mlkem.DecapsulateTemps → Result Unit

/-- [symcrust::sha3::keccak4x::{impl core::ops::drop::Drop for symcrust::sha3::keccak4x::Keccak4x}::drop]:
    Source: 'src/sha3/keccak4x.rs', lines 98:4-104:5
    Visibility: public -/
axiom sha3.keccak4x.Keccak4x.Insts.CoreOpsDropDrop.drop
  : sha3.keccak4x.Keccak4x → Result sha3.keccak4x.Keccak4x

/-- [symcrust::sha3::keccak4x_hybrid::load_lane]:
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 148:0-150:1

    Modelled as the lane-typed `Lane4 ↔ m256` view, retyped to the concrete
    byte carrier `m256 = Array U8 32` after the AVX2 cfg-swap redirect.
    `Lane4 = Array U64 4` is `#[repr(C, align(32))]` in Rust, same bit-layout
    as a 256-bit YMM register; `Intrinsics.X86_64.m256.ofU64x4` is the derived
    pure converter on top of the `m256.{u8x32, ofU8x32}` byte-view axioms.
    No new axiom. -/
noncomputable def sha3.keccak4x_hybrid.load_lane
    (l : sha3.keccak4x_hybrid.Lane4) : Result (Std.Array Std.U8 32#usize) :=
  ok (Intrinsics.X86_64.m256.ofU64x4 l)

/-- [symcrust::sha3::keccak4x_hybrid::store_lane]:
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 155:0-157:1

    Modelled as the lane-typed `m256 ↔ Lane4` view, retyped to the concrete
    byte carrier `m256 = Array U8 32`. The Rust signature takes `&mut Lane4`
    as the destination; the extracted Lean signature passes the prior `Lane4`
    by value and returns the new one — we discard the prior value and return
    the `u64x4` view of the input register. No new axiom. -/
noncomputable def sha3.keccak4x_hybrid.store_lane
    (_ : sha3.keccak4x_hybrid.Lane4) (m : Std.Array Std.U8 32#usize)
    : Result sha3.keccak4x_hybrid.Lane4 :=
  ok (Intrinsics.X86_64.m256.u64x4 m)

/-- [symcrust::sha3::keccak4x_hybrid::{impl core::ops::drop::Drop for symcrust::sha3::keccak4x_hybrid::Keccak4xHybrid}::drop]:
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 200:4-206:5
    Visibility: public -/
axiom sha3.keccak4x_hybrid.Keccak4xHybrid.Insts.CoreOpsDropDrop.drop
  :
  sha3.keccak4x_hybrid.Keccak4xHybrid → Result
    sha3.keccak4x_hybrid.Keccak4xHybrid

