-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
-- @codified (carrier-concretization): the opaque `axiom core.core_arch.x86.__m128i
-- : Type` that Aeneas emits is stripped from `TypesExternal_Template.lean` by
-- `scripts/prune-external-template.py`, which also injects the `import` below.
-- The concrete `@[rust_type] def core.core_arch.x86.__m128i := Intrinsics.M128`
-- (= `Array U8 16`) is the single source of truth in `Intrinsics/Simd.lean` (a
-- leaf importing only `Aeneas`, so there is no import cycle).
import Intrinsics.Simd
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- [core::core_arch::x86::__m128i]: the `@[rust_type]` binding + concrete carrier
   def live in `Intrinsics/Simd.lean` (imported above); the opaque axiom Aeneas
   emits here is pruned by `scripts/prune-external-template.py`. -/

/-- [symcrust::common::InPlaceOrDisjointBuffer]
    Source: 'src/common.rs', lines 214:0-219:1
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer (T : Type) : Type
