-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
-- @injected by scripts/prune-external-template.py (start)
import Intrinsics.Simd
-- @injected by scripts/prune-external-template.py (end)
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [symcrust::common::InPlaceOrDisjointBuffer]
    Source: 'src/common.rs', lines 152:0-157:1
    Visibility: public -/
axiom common.InPlaceOrDisjointBuffer (T : Type) : Type
