-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: type definitions
import Aeneas
import Symcrust.Code.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace symcrust

/-- [symcrust::common::Error]
    Source: 'src/common.rs', lines 32:0-56:1
    Visibility: public -/
@[discriminant isize [0,32768,32769,32770,32771,32772,32773,32774,32775,32776,32777,32778,32779,32780,32781,32782,32783,32784,32785,32786,32787,32788,32789]]
inductive common.Error where
| NoError : common.Error
| Unused : common.Error
| WrongKeySize : common.Error
| WrongBlockSize : common.Error
| WrongDataSize : common.Error
| WrongNonceSize : common.Error
| WrongTagSize : common.Error
| WrongIterationCount : common.Error
| AuthenticationFailure : common.Error
| ExternalFailure : common.Error
| FipsFailure : common.Error
| HardwareFailure : common.Error
| NotImplemented : common.Error
| InvalidBlob : common.Error
| BufferTooSmall : common.Error
| InvalidArgument : common.Error
| MemoryAllocationFailure : common.Error
| SignatureVerificationFailure : common.Error
| IncompatibleFormat : common.Error
| ValueTooLarge : common.Error
| SessionReplayFailure : common.Error
| HbsNoOtsKeysLeft : common.Error
| HbsPublicRootMismatch : common.Error

/-- [symcrust::common::SelftestAlgorithm]
    Source: 'src/common.rs', lines 60:0-72:1
    Visibility: public -/
@[discriminant isize [0,1,2,4,8,16,32,64,128,256,512]]
inductive common.SelftestAlgorithm where
| NONE : common.SelftestAlgorithm
| STARTUP : common.SelftestAlgorithm
| DSA : common.SelftestAlgorithm
| ECDSA : common.SelftestAlgorithm
| RSA : common.SelftestAlgorithm
| DH : common.SelftestAlgorithm
| ECDH : common.SelftestAlgorithm
| MLKEM : common.SelftestAlgorithm
| XMSS : common.SelftestAlgorithm
| LMS : common.SelftestAlgorithm
| MLDSA : common.SelftestAlgorithm

/-- Trait declaration: [symcrust::common::BoxDefault]
    Source: 'src/common.rs', lines 293:0-300:1
    Visibility: public -/
structure common.BoxDefault (Self : Type) where
  box_default : MutRawPtr Self → Result Unit

/-- Trait declaration: [symcrust::hash::HashParams]
    Source: 'src/hash.rs', lines 7:0-10:1 -/
structure hash.HashParams (Self : Type) where
  RESULT_SIZE : Result Std.Usize
  BLOCK_SIZE : Result Std.U32

/-- Trait declaration: [symcrust::hash::StatefulHash]
    Source: 'src/hash.rs', lines 12:0-42:1
    Visibility: public -/
structure hash.StatefulHash (Self : Type) (RESULT_SIZE1 : Std.Usize)
  (BLOCK_SIZE1 : Std.U32) where
  RESULT_SIZE : Result Std.Usize
  BLOCK_SIZE : Result Std.U32
  new : Result Self
  append : Self → Slice Std.U8 → Result Self
  result : Self → Array Std.U8 RESULT_SIZE1 → Result (Self × (Array Std.U8
    RESULT_SIZE1))
  import_state : Self → Result Self
  export_state : Self → Result Unit

/-- Trait declaration: [symcrust::hash::OneShotHash]
    Source: 'src/hash.rs', lines 44:0-57:1
    Visibility: public -/
structure hash.OneShotHash (Self : Type) (RESULT_SIZE1 : Std.Usize)
  (BLOCK_SIZE1 : Std.U32) where
  RESULT_SIZE : Result Std.Usize
  BLOCK_SIZE : Result Std.U32
  hash : Slice Std.U8 → Array Std.U8 RESULT_SIZE1 → Result (Array Std.U8
    RESULT_SIZE1)
  self_test : Result Unit

/-- Trait declaration: [symcrust::hash::StatefulXof]
    Source: 'src/hash.rs', lines 59:0-99:1
    Visibility: public -/
structure hash.StatefulXof (Self : Type) (RESULT_SIZE1 : Std.Usize)
  (BLOCK_SIZE1 : Std.U32) where
  RESULT_SIZE : Result Std.Usize
  BLOCK_SIZE : Result Std.U32
  new : Result Self
  append : Self → Slice Std.U8 → Result Self
  extract : Self → Slice Std.U8 → Bool → Result (Self × (Slice Std.U8))
  result : Self → Array Std.U8 RESULT_SIZE1 → Result (Self × (Array Std.U8
    RESULT_SIZE1))

/-- Trait declaration: [symcrust::hash::OneShotXof]
    Source: 'src/hash.rs', lines 101:0-115:1
    Visibility: public -/
structure hash.OneShotXof (Self : Type) (RESULT_SIZE1 : Std.Usize) (BLOCK_SIZE1
  : Std.U32) where
  RESULT_SIZE : Result Std.Usize
  BLOCK_SIZE : Result Std.U32
  xof : Slice Std.U8 → Slice Std.U8 → Result (Slice Std.U8)
  self_test : Result Unit

/-- [symcrust::mlkem::hash::MlKemHashAlg]
    Source: 'src/mlkem/hash.rs', lines 25:0-32:1 -/
@[discriminant isize]
inductive mlkem.hash.MlKemHashAlg where
| None : mlkem.hash.MlKemHashAlg
| Shake128 : mlkem.hash.MlKemHashAlg
| Shake256 : mlkem.hash.MlKemHashAlg
| Sha3_256 : mlkem.hash.MlKemHashAlg
| Sha3_512 : mlkem.hash.MlKemHashAlg

/-- [symcrust::sha3::sha3_impl::KeccakState]
    Source: 'src/sha3/sha3_impl.rs', lines 36:0-45:1 -/
structure sha3.sha3_impl.KeccakState where
  state : Array Std.U64 25#usize
  input_block_size : Std.U32
  state_index : Std.U32
  padding_value : Std.U8
  squeeze_mode : Bool

/-- [symcrust::mlkem::hash::MlKemHashState]
    Source: 'src/mlkem/hash.rs', lines 40:0-43:1 -/
structure mlkem.hash.MlKemHashState where
  state : sha3.sha3_impl.KeccakState
  alg : mlkem.hash.MlKemHashAlg

/-- [symcrust::sha3::shake_variants::OneShotShake]
    Source: 'src/sha3/shake_variants.rs', lines 67:0-67:71
    Visibility: public -/
@[reducible]
def sha3.shake_variants.OneShotShake (RESULT_SIZE : Std.Usize) (BLOCK_SIZE :
  Std.U32) :=
Unit

/-- [symcrust::sha3::sha3_variants::OneShotSha3]
    Source: 'src/sha3/sha3_variants.rs', lines 85:0-85:70
    Visibility: public -/
@[reducible]
def sha3.sha3_variants.OneShotSha3 (RESULT_SIZE : Std.Usize) (BLOCK_SIZE :
  Std.U32) :=
Unit

/-- [symcrust::mlkem::key::Format]
    Source: 'src/mlkem/key.rs', lines 23:0-36:1
    Visibility: public -/
@[discriminant isize [1,2,3]]
inductive mlkem.key.Format where
| PrivateSeed : mlkem.key.Format
| DecapsulationKey : mlkem.key.Format
| EncapsulationKey : mlkem.key.Format

/-- [symcrust::mlkem::key::Params]
    Source: 'src/mlkem/key.rs', lines 39:0-45:1
    Visibility: public -/
@[discriminant isize [1,2,3]]
inductive mlkem.key.Params where
| MlKem512 : mlkem.key.Params
| MlKem768 : mlkem.key.Params
| MlKem1024 : mlkem.key.Params

/-- [symcrust::mlkem::key::InternalParams]
    Source: 'src/mlkem/key.rs', lines 47:0-65:1 -/
structure mlkem.key.InternalParams where
  params : mlkem.key.Params
  n_rows : Std.U8
  n_eta1 : Std.U8
  n_eta2 : Std.U8
  n_bits_of_u : Std.U8
  n_bits_of_v : Std.U8

/-- [symcrust::mlkem::key::Key]
    Source: 'src/mlkem/key.rs', lines 123:0-160:1
    Visibility: public -/
structure mlkem.key.Key where
  algorithm_info : Std.U32
  has_private_seed : Bool
  has_private_key : Bool
  private_seed : Array Std.U8 32#usize
  private_random : Array Std.U8 32#usize
  public_seed : Array Std.U8 32#usize
  encoded_t : Array Std.U8 1536#usize
  encaps_key_hash : Array Std.U8 32#usize
  params : mlkem.key.InternalParams
  n_rows : Std.Usize
  data : Array (Array Std.U16 256#usize) 24#usize

/-- [symcrust::mlkem::ntt::InternalComputationTemporaries]
    Source: 'src/mlkem/ntt.rs', lines 55:0-63:1 -/
structure mlkem.ntt.InternalComputationTemporaries where
  max_size_vector0 : Array (Array Std.U16 256#usize) 4#usize
  max_size_vector1 : Array (Array Std.U16 256#usize) 4#usize
  poly_element0 : Array Std.U16 256#usize
  poly_element1 : Array Std.U16 256#usize
  poly_element_accumulator : Array Std.U32 256#usize
  hash_state0 : mlkem.hash.MlKemHashState
  hash_state1 : mlkem.hash.MlKemHashState

/-- [symcrust::sha3::sha3_variants::Sha3State]
    Source: 'src/sha3/sha3_variants.rs', lines 38:0-40:1
    Visibility: public -/
structure sha3.sha3_variants.Sha3State (RESULT_SIZE : Std.Usize) (BLOCK_SIZE :
  Std.U32) where
  state : sha3.sha3_impl.KeccakState

/-- [symcrust::mlkem::ntt::ntt_neon::NttIntrinsicsNeon]
    Source: 'src/mlkem/ntt_neon.rs', lines 56:0-56:36 -/
@[reducible]
def mlkem.ntt.ntt_neon.NttIntrinsicsNeon := Unit

/-- Trait declaration: [symcrust::mlkem::ntt::NttIntrinsicsInterface]
    Source: 'src/mlkem/ntt.rs', lines 253:0-269:1 -/
structure mlkem.ntt.NttIntrinsicsInterface (Self : Type) (Self_Vec128 : Type)
  where
  coremarkerCopyInst : core.marker.Copy Self_Vec128
  vec128_load_u16x8 : Array Std.U16 256#usize → Std.Usize → Result
    Self_Vec128
  vec64_load_u16x4 : Array Std.U16 256#usize → Std.Usize → Result
    Self_Vec128
  vec32_load_u16x2 : Array Std.U16 256#usize → Std.Usize → Result
    Self_Vec128
  vec128_store_u16x8 : Array Std.U16 256#usize → Std.Usize → Self_Vec128
    → Result (Array Std.U16 256#usize)
  vec64_store_u16x4 : Array Std.U16 256#usize → Std.Usize → Self_Vec128 →
    Result (Array Std.U16 256#usize)
  vec32_store_u16x2 : Array Std.U16 256#usize → Std.Usize → Self_Vec128 →
    Result (Array Std.U16 256#usize)
  vec128_set_u16x8 : Std.U16 → Result Self_Vec128
  vec128_mod_sub : Self_Vec128 → Self_Vec128 → Result Self_Vec128
  vec128_mod_add : Self_Vec128 → Self_Vec128 → Result Self_Vec128
  vec128_mont_mul : Self_Vec128 → Self_Vec128 → Self_Vec128 → Result
    Self_Vec128

/-- [symcrust::mlkem::ntt::ntt_xmm::NttIntrinsicsXmm]
    Source: 'src/mlkem/ntt_xmm.rs', lines 62:0-62:35 -/
@[reducible]
def mlkem.ntt.ntt_xmm.NttIntrinsicsXmm := Unit

/-- [symcrust::mlkem::DecapsulateTemps]
    Source: 'src/mlkem/mlkem.rs', lines 769:0-773:1 -/
structure mlkem.DecapsulateTemps where
  comp_temps : mlkem.ntt.InternalComputationTemporaries
  read_ciphertext : Array Std.U8 1568#usize
  reencapsulated_ciphertext : Array Std.U8 1568#usize

/-- [symcrust::sha3::keccak4x::Lane4]
    Source: 'src/sha3/keccak4x.rs', lines 24:0-24:34 -/
@[reducible]
def sha3.keccak4x.Lane4 := Array Std.U64 4#usize

/-- [symcrust::sha3::keccak4x::Keccak4x]
    Source: 'src/sha3/keccak4x.rs', lines 86:0-88:1
    Visibility: public -/
structure sha3.keccak4x.Keccak4x where
  state : Array sha3.keccak4x.Lane4 25#usize

/-- [symcrust::sha3::keccak4x_hybrid::Lane4]
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 96:0-96:34 -/
@[reducible]
def sha3.keccak4x_hybrid.Lane4 := Array Std.U64 4#usize

/-- [symcrust::sha3::keccak4x_hybrid::Keccak4xHybrid]
    Source: 'src/sha3/keccak4x_hybrid.rs', lines 200:0-202:1
    Visibility: public -/
structure sha3.keccak4x_hybrid.Keccak4xHybrid where
  state : Array sha3.keccak4x_hybrid.Lane4 25#usize

/-- [symcrust::sha3::sha3_variants::Sha3_224Params]
    Source: 'src/sha3/sha3_variants.rs', lines 12:0-12:22 -/
@[reducible]
def sha3.sha3_variants.Sha3_224Params := Unit

/-- [symcrust::sha3::sha3_variants::Sha3_256Params]
    Source: 'src/sha3/sha3_variants.rs', lines 13:0-13:22 -/
@[reducible]
def sha3.sha3_variants.Sha3_256Params := Unit

/-- [symcrust::sha3::sha3_variants::Sha3_384Params]
    Source: 'src/sha3/sha3_variants.rs', lines 14:0-14:22 -/
@[reducible]
def sha3.sha3_variants.Sha3_384Params := Unit

/-- [symcrust::sha3::sha3_variants::Sha3_512Params]
    Source: 'src/sha3/sha3_variants.rs', lines 15:0-15:22 -/
@[reducible]
def sha3.sha3_variants.Sha3_512Params := Unit

/-- [symcrust::sha3::shake1x::HXof]
    Source: 'src/sha3/shake1x.rs', lines 34:0-36:1 -/
structure sha3.shake1x.HXof where
  state : sha3.sha3_impl.KeccakState

/-- [symcrust::sha3::shake1x::GXof]
    Source: 'src/sha3/shake1x.rs', lines 60:0-62:1 -/
structure sha3.shake1x.GXof where
  state : sha3.sha3_impl.KeccakState

/-- [symcrust::sha3::shake1x::Sha3_256State]
    Source: 'src/sha3/shake1x.rs', lines 88:0-90:1 -/
structure sha3.shake1x.Sha3_256State where
  state : sha3.sha3_impl.KeccakState

/-- [symcrust::sha3::shake1x::Sha3_512State]
    Source: 'src/sha3/shake1x.rs', lines 117:0-119:1 -/
structure sha3.shake1x.Sha3_512State where
  state : sha3.sha3_impl.KeccakState

/-- [symcrust::sha3::shake4x::Shake4x]
    Source: 'src/sha3/shake4x.rs', lines 20:0-29:1 -/
structure sha3.shake4x.Shake4x where
  state : sha3.keccak4x_hybrid.Keccak4xHybrid
  rate : Std.Usize
  rate_lanes : Std.Usize
  buf : Array (Array Std.U8 168#usize) 4#usize
  absorbed : Array Std.Usize 4#usize
  finalized : Bool

/-- [symcrust::sha3::shake_variants::Shake128Params]
    Source: 'src/sha3/shake_variants.rs', lines 12:0-12:22 -/
@[reducible]
def sha3.shake_variants.Shake128Params := Unit

/-- [symcrust::sha3::shake_variants::Shake256Params]
    Source: 'src/sha3/shake_variants.rs', lines 13:0-13:22 -/
@[reducible]
def sha3.shake_variants.Shake256Params := Unit

/-- [symcrust::sha3::shake_variants::ShakeState]
    Source: 'src/sha3/shake_variants.rs', lines 26:0-28:1
    Visibility: public -/
structure sha3.shake_variants.ShakeState (RESULT_SIZE : Std.Usize) (BLOCK_SIZE
  : Std.U32) where
  state : sha3.sha3_impl.KeccakState

end symcrust
