#!/usr/bin/env python3
#
# Generate export files for symcrypt_plus_testmodule from one hand-maintained
# local DEF listing the symbols this module provides directly
# (SymCryptModuleInit + the SymCryptHpke* surface):
#   --out     : combined Windows DEF. Every base export from --base that is not
#               already in --local is emitted as a forwarder of the form
#               "Name = symcrypttestmodule.Name [DATA]".
#   --out-ver : ELF version script.
#   --out-osx : Darwin exported-symbols list.
#
# This keeps the local plus export surface in exactly one source file.
#
# Copyright (c) Microsoft Corporation. Licensed under the MIT license.
#
import argparse
import re
import sys

# Matches one DEF export entry: name, optional " DATA", optional trailing
# "; comment". Forwarder entries (containing "=") are intentionally not
# matched; this script never reads forwarders from its inputs and never emits
# anything back into them.
EXPORT_RE = re.compile(r"^\s+([A-Za-z_]\w*)(\s+DATA)?\s*(?:;.*)?$")


def local_exports(path):
    """Return local export names from a DEF, preserving first-seen order."""
    seen = set()
    names = []
    with open(path) as f:
        for line in f:
            m = EXPORT_RE.match(line)
            if m:
                name = m.group(1)
                if name not in seen:
                    seen.add(name)
                    names.append(name)
    return names


def write_combined_def(path, local_path, base_path, local_names):
    with open(local_path) as f:
        local_text = f.read().rstrip()

    local_names_set = set(local_names)
    with open(path, "w") as out:
        out.write(local_text)
        out.write("\n\n")
        out.write("    ; Forwarders to symcrypttestmodule (auto-generated from its exports.def)\n")
        with open(base_path) as base:
            for line in base:
                m = EXPORT_RE.match(line)
                if not m:
                    continue
                name = m.group(1)
                if name in local_names_set:
                    continue
                data = " DATA" if m.group(2) else ""
                out.write(f"    {name} = symcrypttestmodule.{name}{data}\n")


def write_version_script(path, local_names):
    with open(path, "w") as out:
        out.write("# Generated by gen_combined_def.py from exports_plus_local.def.\n")
        out.write("# Do not edit directly.\n\n")
        out.write("VERSION_HPKE_PLUS_1.0 {\n")
        out.write("    global:\n")
        for name in local_names:
            out.write(f"        {name};\n")
        out.write("\n")
        out.write("    local: *;\n")
        out.write("};\n")


def write_darwin_exports(path, local_names):
    with open(path, "w") as out:
        for name in local_names:
            out.write(f"_{name}\n")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--base", help="symcrypttestmodule's exports.def (required with --out)")
    p.add_argument("--local", required=True, help="hand-maintained local exports DEF")
    p.add_argument("--out", help="generated combined Windows DEF")
    p.add_argument("--out-ver", help="generated ELF version script")
    p.add_argument("--out-osx", help="generated Darwin exported-symbols list")
    args = p.parse_args()

    if not (args.out or args.out_ver or args.out_osx):
        p.error("at least one of --out, --out-ver, or --out-osx is required")
    if args.out and not args.base:
        p.error("--base is required when --out is used")

    local_names = local_exports(args.local)

    if args.out:
        write_combined_def(args.out, args.local, args.base, local_names)
    if args.out_ver:
        write_version_script(args.out_ver, local_names)
    if args.out_osx:
        write_darwin_exports(args.out_osx, local_names)


if __name__ == "__main__":
    sys.exit(main())
