parameters:
- name: arch
  type: string
  values:
  - AMD64
  - X86
  - ARM64
  - ARM
- name: config
  type: string
  values:
  - Debug
  - Release
  - Sanitize
- name: cc
  type: string
  values:
  - gcc
  - clang
- name: cxx
  type: string
  values:
  - g++
  - clang++
- name: skipTests # Skip time-consuming tests for PR builds (e.g. no-ASM build)
  type: boolean
  default: false
- name: additionalArgs # Additional arguments to pass to the build script
  type: string
  default: ''
- name: identifier # Additional identifier for job name
  type: string
  default: ''
- name: openssl # Build with OpenSSL
  type: boolean
  default: false

jobs:
- job: Linux_${{ parameters.arch}}_${{ parameters.cc }}_${{parameters.config}}_${{parameters.identifier}}
  displayName: Linux ${{ parameters.arch}} ${{ parameters.cc }} ${{parameters.config}} ${{ parameters.identifier }}

  pool:
    type: linux

  variables:
    ob_outputDirectory: $(Build.SourcesDirectory)/bin
    ob_sdl_binskim_break: ${{ eq(parameters.config, 'Release') }} # Only break on binskim failures for Release binaries https://aka.ms/obpipelines/sdl
    ${{ if eq(variables['system.debug'], true) }}:
      verbose_build_flag: '--verbose'
    ${{ else }}:
      verbose_build_flag: ''
    ${{ if eq(parameters.openssl, true) }}:
      openssl_build_flag: '--openssl-build-from-source'
    ${{ else }}:
      openssl_build_flag: ''

  steps:
    - script: |
        apt-get update -y
      displayName: 'Update package manager'

    - ${{ if eq(parameters.cc, 'clang') }}:
      # Install clang-11 and manually add symlinks so that it can be run via just "clang" rather
      # than clang-11. This is required because we can't explicitly specify clang-11 for
      # parameters.cc (it breaks the job name, because job names aren't allowed to have '-' in them)
      - script: |
          apt-get install -y clang-11
          ln -s /usr/bin/clang-11 /usr/bin/clang
          ln -s /usr/bin/clang++-11 /usr/bin/clang++
        displayName: 'Install clang'

    - ${{ if eq(parameters.arch, 'X86') }}:
      - script: |
          apt-get install -y gcc-multilib g++-multilib
        displayName: 'Install x86 headers and libraries'

    # Note: this assumes that the pipeline is always running on an AMD64 machine. When we have
    # native ARM64 pipelines, we'll need to change this.
    - ${{ if eq(parameters.arch, 'ARM64') }}:
      - script: |
          apt-get install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user
        displayName: 'Install arm64 cross-compilation tools'

    - ${{ if eq(parameters.arch, 'ARM') }}:
      - script: |
          apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf qemu-user
        displayName: 'Install arm cross-compilation tools'

    # TODO: Once we move to Azure Linux 3 we can use the system-provided OpenSSL package.
    # For now we will built from source since Ubuntu 20.04 doesn't have OpenSSL 3.
    # - ${{ if eq(parameters.openssl, true) }}:
    #   - script: |
    #       apt-get install -y libssl-dev
    #     displayName: 'Install OpenSSL'

    - task: PipAuthenticate@1
      inputs:
        artifactFeeds: 'OS/SymCrypt_PublicPackages'

    - script: |
        pip install -v -r scripts/requirements.txt
      displayName: 'Install Python dependencies'

    - task: PythonScript@0
      displayName: 'Run build script'
      inputs:
        scriptSource: 'filePath'
        scriptPath: scripts/build.py
        arguments: 'cmake bin --arch ${{ parameters.arch }} --config ${{ parameters.config }} --cc ${{ parameters.cc }} --cxx ${{ parameters.cxx }} ${{ parameters.additionalArgs }} $(verbose_build_flag) $(openssl_build_flag)'
        workingDirectory: $(Build.SourcesDirectory)

    # Overwrite default artifact publishing with our copy (enables publishing binaries for failed runs)
    - script: |
          cp .artifactignore "$(ob_outputDirectory)/.artifactignore"
      displayName: 'Overwrite .artifactignore'

    - ${{ if ne(parameters.skipTests, true) }}:
      - ${{ if ne(parameters.arch, 'ARM64') }}:
        - ${{ if ne(parameters.arch, 'ARM') }}:
          - task: PythonScript@0
            displayName: 'Run unit tests'
            inputs:
              scriptSource: 'filePath'
              scriptPath: scripts/test.py
              arguments: 'bin noperftests'
              workingDirectory: $(Build.SourcesDirectory)

          - ${{ if ne(parameters.config, 'Sanitize') }}:
            - task: PythonScript@0
              displayName: 'Run dynamic unit tests'
              inputs:
                scriptSource: 'filePath'
                scriptPath: scripts/test.py
                arguments: 'bin dynamic:bin/module/generic/libsymcrypt.so noperftests'
                workingDirectory: $(Build.SourcesDirectory)

      - ${{ if eq(parameters.arch, 'AMD64') }}:
        - task: PythonScript@0
          displayName: 'Run unit tests (test YMM save/restore)'
          inputs:
            scriptSource: 'filePath'
            scriptPath: scripts/test.py
            arguments: '--glibc-disable-ymm bin testSaveYmm'
            workingDirectory: $(Build.SourcesDirectory)

      - ${{ if eq(parameters.arch, 'ARM64') }}:
        - task: PythonScript@0
          displayName: 'Run unit tests'
          inputs:
            scriptSource: 'filePath'
            scriptPath: scripts/test.py
            arguments: '--emulator qemu-aarch64 --emulator-lib-dir /usr/aarch64-linux-gnu/ bin noperftests +symcrypt -dh -dsa -rsa'
            workingDirectory: $(Build.SourcesDirectory)

        - task: PythonScript@0
          displayName: 'Run dynamic unit tests'
          inputs:
            scriptSource: 'filePath'
            scriptPath: scripts/test.py
            arguments: '--emulator qemu-aarch64 --emulator-lib-dir /usr/aarch64-linux-gnu/ bin dynamic:bin/module/generic/libsymcrypt.so noperftests +symcrypt -dh -dsa -rsa'
            workingDirectory: $(Build.SourcesDirectory)

      - ${{ if eq(parameters.arch, 'ARM') }}:
        - task: PythonScript@0
          displayName: 'Run unit tests'
          inputs:
            scriptSource: 'filePath'
            scriptPath: scripts/test.py
            arguments: '--emulator qemu-arm --emulator-lib-dir /usr/arm-linux-gnueabihf/ bin noperftests +symcrypt -dh -dsa -rsa'
            workingDirectory: $(Build.SourcesDirectory)

        - task: PythonScript@0
          displayName: 'Run dynamic unit tests'
          inputs:
            scriptSource: 'filePath'
            scriptPath: scripts/test.py
            arguments: '--emulator qemu-arm --emulator-lib-dir /usr/arm-linux-gnueabihf/ bin dynamic:bin/module/generic/libsymcrypt.so noperftests +symcrypt -dh -dsa -rsa'
            workingDirectory: $(Build.SourcesDirectory)

    - task: PythonScript@0
      displayName: 'Package generic Linux module'
      inputs:
        scriptSource: 'filePath'
        scriptPath: scripts/package.py
        arguments: 'bin ${{ parameters.arch }} ${{ parameters.config }} generic bin'
        workingDirectory: $(Build.SourcesDirectory)

    - task: Bash@3
      displayName: 'Check if OpenEnclave module exists'
      inputs:
        targetType: inline
        script: |
          if [ -d bin/module/oe_full ]; then
            echo "##vso[task.setVariable variable=PACKAGE_OE]true"
          fi

    - task: PythonScript@0
      displayName: 'Package OpenEnclave module'
      condition: eq(variables.PACKAGE_OE, 'true')
      inputs:
        scriptSource: 'filePath'
        scriptPath: scripts/package.py
        arguments: 'bin ${{ parameters.arch }} ${{ parameters.config }} oe_full bin'
        workingDirectory: $(Build.SourcesDirectory)
