//
// Test FIPS Approved Services Indicator
//
// Copyright (c) Microsoft Corporation. Licensed under the MIT license. 
//

#include "precomp.h"

#define SYMCRYPT_SI_NO_PARAMS 0, 0, 0

#define CHECK_APPROVED(svc, alg, ...)       CHECK(SymCryptDeprecatedServiceIndicator(svc, alg, __VA_ARGS__) == 0, "?")

#define CHECK_NONAPPROVED(svc, alg, ...)    CHECK(SymCryptDeprecatedServiceIndicator(svc, alg, __VA_ARGS__) != 0, "?")


VOID
testApprovedAlgorithms()
{
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_CBC,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_CCM,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_CFB128, SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_CFB8,   SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_CTR,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_ECB,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_GCM,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_XTS,    SYMCRYPT_SI_KEYBITS(128), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_AES_XTS,    SYMCRYPT_SI_KEYBITS(256), 0, 0 );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_CBC,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_CCM,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_CFB128, SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_CFB8,   SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_CTR,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_ECB,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_GCM,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_XTS,    SYMCRYPT_SI_KEYBITS(128), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_AES_XTS,    SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_DECRYPTION, SYMCRYPT_SI_RSA_DEC_PRIM, SYMCRYPT_SI_MODULUS(2048), 0, 0 );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA1,      SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA2_256,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA2_384,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA2_512,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA3_256,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA3_384,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA3_512,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHAKE128,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHAKE256,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_CSHAKE128, SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_CSHAKE256, SYMCRYPT_SI_NO_PARAMS );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA1,      SYMCRYPT_SI_KEYBITS(112), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA1,      SYMCRYPT_SI_KEYBITS(128), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA1,      SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA2_256,  SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA2_384,  SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA2_512,  SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA3_256,  SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA3_384,  SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_SHA3_512,  SYMCRYPT_SI_KEYBITS(256), 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_AES_CMAC,       SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_AES_GMAC,       SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_KMAC128,        SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_KMAC256,        SYMCRYPT_SI_NO_PARAMS );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA1, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA2_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA2_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA2_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA3_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA3_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_SHA3_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA1, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA2_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA2_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA2_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA3_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA3_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_HMAC_SHA3_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_KMAC128, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDA_ONESTEP, SYMCRYPT_SI_KMAC256, 0, 0 );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA1, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA2_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA2_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA2_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA3_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA3_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_PBKDF, SYMCRYPT_SI_HMAC_SHA3_512, 0, 0 );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_AES_CMAC, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA1, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA2_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA2_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA2_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA3_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA3_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SP800_108_CTR, SYMCRYPT_SI_HMAC_SHA3_512, 0, 0 );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SRTP,       SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SSH,        SYMCRYPT_SI_SHA1, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SSH,        SYMCRYPT_SI_SHA2_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SSH,        SYMCRYPT_SI_SHA2_384, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_SSH,        SYMCRYPT_SI_SHA2_512, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_TLS,        SYMCRYPT_SI_NO_PARAMS );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_TLS_V12,    SYMCRYPT_SI_SHA2_256, 0, 0 );
    CHECK_APPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_KDF_TLS_V12,    SYMCRYPT_SI_SHA2_384, 0, 0 );

    CHECK_APPROVED( SYMCRYPT_SI_SVC_RANDOM_NUMBER_GENERATION, SYMCRYPT_SI_CTR_DRBG_AES256, SYMCRYPT_SI_NO_PARAMS);

    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_ECDSA_KEYGEN, SYMCRYPT_SI_ECURVE_NISTP256, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_ECDSA_KEYGEN, SYMCRYPT_SI_ECURVE_NISTP384, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_ECDSA_KEYGEN, SYMCRYPT_SI_ECURVE_NISTP521, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_RSA_KEYGEN, SYMCRYPT_SI_MODULUS(2048), 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_RSA_KEYGEN, SYMCRYPT_SI_MODULUS(3072), 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_RSA_KEYGEN, SYMCRYPT_SI_MODULUS(4096), 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_FFDHE_2048, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_FFDHE_3072, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_FFDHE_4096, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_FFDHE_6144, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_MODP_2048, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_MODP_3072, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_MODP_4096, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_SAFE_PRIME_KEYGEN, SYMCRYPT_SI_SPG_MODP_6144, 0, 0);

    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_VERIFICATION, SYMCRYPT_SI_DSA_PQGVER, SYMCRYPT_SI_DSAPARAMS(2048, 256), 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_VERIFICATION, SYMCRYPT_SI_DSA_PQGVER, SYMCRYPT_SI_DSAPARAMS(3072, 256), 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_VERIFICATION, SYMCRYPT_SI_ECDSA_KEYVER, SYMCRYPT_SI_ECURVE_NISTP256, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_VERIFICATION, SYMCRYPT_SI_ECDSA_KEYVER, SYMCRYPT_SI_ECURVE_NISTP384, 0, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_VERIFICATION, SYMCRYPT_SI_ECDSA_KEYVER, SYMCRYPT_SI_ECURVE_NISTP521, 0, 0);
    
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_ECDSA_SIGGEN,         SYMCRYPT_SI_ECURVE_NISTP256, SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_ECDSA_SIGGEN,         SYMCRYPT_SI_ECURVE_NISTP384, SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_ECDSA_SIGGEN,         SYMCRYPT_SI_ECURVE_NISTP521, SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_ECDSA_SIGGEN_COMP,    SYMCRYPT_SI_ECURVE_NISTP256, SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_ECDSA_SIGGEN_COMP,    SYMCRYPT_SI_ECURVE_NISTP384, SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_ECDSA_SIGGEN_COMP,    SYMCRYPT_SI_ECURVE_NISTP521, SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCS15,    SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIGGEN_PKCSPSS,   SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_RSA_SIG_PRIM,         SYMCRYPT_SI_NO_PARAMS);
    
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_DSA_SIGVER,         SYMCRYPT_SI_DSAPARAMS(2048, 256), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_DSA_SIGVER,         SYMCRYPT_SI_DSAPARAMS(3072, 256), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_ECDSA_SIGVER,       SYMCRYPT_SI_ECURVE_NISTP256, SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_ECDSA_SIGVER,       SYMCRYPT_SI_ECURVE_NISTP384, SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_ECDSA_SIGVER,       SYMCRYPT_SI_ECURVE_NISTP521, SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCS15,  SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(1024), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(2048), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(3072), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA1, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIGVER_PKCSPSS, SYMCRYPT_SI_MODULUS(4096), SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_RSA_SIG_PRIM,       SYMCRYPT_SI_NO_PARAMS);
    
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_ECC,      SYMCRYPT_SI_ECURVE_NISTP256,    SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_ECC,      SYMCRYPT_SI_ECURVE_NISTP384,    SYMCRYPT_SI_SHA2_384, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_ECC,      SYMCRYPT_SI_ECURVE_NISTP521,    SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_ECC_SSC,  SYMCRYPT_SI_ECURVE_NISTP256,    SYMCRYPT_SI_SCHEME_EPHEM_UNIFIED, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_ECC_SSC,  SYMCRYPT_SI_ECURVE_NISTP384,    SYMCRYPT_SI_SCHEME_EPHEM_UNIFIED, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_ECC_SSC,  SYMCRYPT_SI_ECURVE_NISTP521,    SYMCRYPT_SI_SCHEME_EPHEM_UNIFIED, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_2048,     SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_3072,     SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_4096,     SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_6144,     SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_2048,      SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_3072,      SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_4096,      SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_6144,      SYMCRYPT_SI_SHA2_256, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_2048,     SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_3072,     SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_4096,     SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_FFDHE_6144,     SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_2048,      SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_3072,      SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_4096,      SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,      SYMCRYPT_SI_SPG_MODP_6144,      SYMCRYPT_SI_SHA2_512, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_2048,     SYMCRYPT_SI_SCHEME_DH_EPHEM, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_3072,     SYMCRYPT_SI_SCHEME_DH_EPHEM, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_4096,     SYMCRYPT_SI_SCHEME_DH_EPHEM, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_2048,      SYMCRYPT_SI_SCHEME_DH_EPHEM, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_3072,      SYMCRYPT_SI_SCHEME_DH_EPHEM, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_4096,      SYMCRYPT_SI_SCHEME_DH_EPHEM, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_2048,     SYMCRYPT_SI_SCHEME_DH_ONEFLOW, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_3072,     SYMCRYPT_SI_SCHEME_DH_ONEFLOW, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_4096,     SYMCRYPT_SI_SCHEME_DH_ONEFLOW, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_2048,      SYMCRYPT_SI_SCHEME_DH_ONEFLOW, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_3072,      SYMCRYPT_SI_SCHEME_DH_ONEFLOW, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_4096,      SYMCRYPT_SI_SCHEME_DH_ONEFLOW, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_2048,     SYMCRYPT_SI_SCHEME_DH_STATIC, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_3072,     SYMCRYPT_SI_SCHEME_DH_STATIC, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_FFDHE_4096,     SYMCRYPT_SI_SCHEME_DH_STATIC, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_2048,      SYMCRYPT_SI_SCHEME_DH_STATIC, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_3072,      SYMCRYPT_SI_SCHEME_DH_STATIC, 0);
    CHECK_APPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,  SYMCRYPT_SI_SPG_MODP_4096,      SYMCRYPT_SI_SCHEME_DH_STATIC, 0);
}

VOID
testNonApprovedAlgorithms()
{
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_CHACHA20,            SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_CHACHA20_POLY1305,   SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_DES,                 SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_TRIPLEDES,           SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_RC2,                 SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ENCRYPTION, SYMCRYPT_SI_RC4,                 SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_MARVIN32,     SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_POLY1305,     SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_MD2,          SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_MD4,          SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_MD5,          SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA2_224,     SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA2_512_224, SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_HASHING, SYMCRYPT_SI_SHA3_224,     SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_AES_CBCMAC,  SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_MD2,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_MD4,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_MESSAGE_AUTHENTICATION, SYMCRYPT_SI_HMAC_MD5,    SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_KEY_DERIVATION, SYMCRYPT_SI_HKDF, SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_SHA1, SYMCRYPT_SI_NO_PARAMS );
    
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_DSA_KEYGEN, SYMCRYPT_SI_DSAPARAMS(2048, 224), 0, 0 );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_DSA_KEYGEN, SYMCRYPT_SI_DSAPARAMS(2048, 256), 0, 0 );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_DSA_KEYGEN, SYMCRYPT_SI_DSAPARAMS(3072, 256), 0, 0 );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_DSA_PQGGEN, SYMCRYPT_SI_DSAPARAMS(2048, 256), 0, 0 );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_DSA_PQGGEN, SYMCRYPT_SI_DSAPARAMS(3072, 256), 0, 0 );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_MLKEM,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_MLDSA,    SYMCRYPT_SI_NO_PARAMS);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_LMS,      SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_XMSS,     SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_ASYMMETRIC_KEY_GENERATION, SYMCRYPT_SI_XMSS_MT,  SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_MLKEM, SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,       SYMCRYPT_SI_SPG_FFDHE_8192, SYMCRYPT_SI_SHA2_256, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,       SYMCRYPT_SI_SPG_FFDHE_8192, SYMCRYPT_SI_SHA2_512, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,       SYMCRYPT_SI_SPG_MODP_8192,  SYMCRYPT_SI_SHA2_256, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC,       SYMCRYPT_SI_SPG_MODP_8192,  SYMCRYPT_SI_SHA2_512, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,   SYMCRYPT_SI_SPG_FFDHE_8192, SYMCRYPT_SI_SHA2_256, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,   SYMCRYPT_SI_SPG_FFDHE_8192, SYMCRYPT_SI_SHA2_512, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,   SYMCRYPT_SI_SPG_MODP_8192,  SYMCRYPT_SI_SHA2_256, 0);
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SECRET_AGREEMENT, SYMCRYPT_SI_KAS_FFC_SSC,   SYMCRYPT_SI_SPG_MODP_8192,  SYMCRYPT_SI_SHA2_512, 0);

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_MLDSA,     SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_LMS,       SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_XMSS,      SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_GENERATION, SYMCRYPT_SI_XMSS_MT,   SYMCRYPT_SI_NO_PARAMS );

    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_MLDSA,   SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_LMS,     SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_XMSS,    SYMCRYPT_SI_NO_PARAMS );
    CHECK_NONAPPROVED( SYMCRYPT_SI_SVC_SIGNATURE_VERIFICATION, SYMCRYPT_SI_XMSS_MT, SYMCRYPT_SI_NO_PARAMS );
}

VOID
testServiceIndicator()
{
    if (!SCTEST_LOOKUP_DISPATCHSYM(SymCryptDeprecatedServiceIndicator))
    {
        print("testServiceIndicator skipped\n");
        return;
    }

    print( "service-indicator\n" );

    testApprovedAlgorithms();

    testNonApprovedAlgorithms();

    print ( "\n" );
}
