################################################################################
#                  OneBranch Pipelines - PR Build                              #
################################################################################
#                                                                              #
# This pipeline is for validation of pull requests. Useful links:              #
#                                                                              #
#   https://www.osgwiki.com/wiki/Windows_Undocked_Template                     #
#   https://aka.ms/obpipelines                                                 #
#   https://aka.ms/obpipelines/yaml/schema                                     #
#   https://aka.ms/obpipelines/tasks                                           #
#   https://aka.ms/onebranchsup                                                #
#                                                                              #
################################################################################

trigger: none # https://aka.ms/obpipelines/triggers

pr:
- main

variables:
  # https://aka.ms/obpipelines/containers
  ONEBRANCH_AME_ACR_LOGIN: onebranch.azurecr.io
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  # https://aka.ms/obpipelines/templates
  template: v2/Microsoft.NonOfficial.yml@templates
  parameters:
    platform:
      name: 'windows_undocked'
    globalSdl:
      isNativeCode: true
      tsa:
        enabled: false # Disable TSA to force build breaks
      policheck:
        break: true # always break the build on policheck issues.
      binskim:
        enabled: false # Temporarily disable binskim until we sort out BA2018 errors
      credscanSuppressionsPath: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
    featureFlags:
      EnableCDPxPAT: false
      WindowsHostVersion: '1ESWindows2022'
    stages:
    - stage: Build
      jobs:
      - template: .pipelines/templates/build-windows-undocked.yml@self
        parameters:
          sln: SymCrypt.sln
          buildType: 'pr'
