/-
  # Encoding/KeySetValue.lean — `key_set_value`.

  `mlkem.key.key_set_value` is the public *decode* entry point for ML-KEM
  keys: it parses a serialised key blob according to the requested
  `MLKEM_BLOB_TYPE` (PrivateSeed / DecapsulationKey / EncapsulationKey)
  and populates `pk_mlkem_key`.  This file collects the `#decompose`
  cascade, `@[step]` specs for every helper, and the top-level
  `mlkem.key_set_value.spec`.

  See `KeyGetValue.lean` for the symmetric encode path. -/
import Symcrust.Properties.MLKEM.Basic
import Symcrust.Properties.MLKEM.Bridges.Encoding
import Symcrust.Properties.MLKEM.Bridges.KeyView
import Symcrust.Properties.MLKEM.Encoding.Compress
import Symcrust.Properties.MLKEM.Encoding.Decompress
import Symcrust.Properties.MLKEM.Ntt.Transpose
import Symcrust.Properties.MLKEM.Sampling.ExpandMatrix
import Symcrust.Properties.MLKEM.Key
import Symcrust.Properties.Stdlib

open Aeneas Aeneas.Std Result
open Spec
open Spec.MLKEM
open symcrust

open scoped Spec.Notations
open symcrust.common
namespace Symcrust.Properties.MLKEM

open Symcrust.Properties.MLKEM.Bridges

set_option maxHeartbeats 4000000
set_option maxRecDepth 4096

/-! ## Local `@[step]` spec for `common.const_time_slices_equal`

The canonical spec lives in `Properties/Stdlib.lean` and is now
imported above (`const_time_slices_equal.spec`).  A thin local re-statement
is kept for callers that prefer the
`a.length = b.length` precondition spelling. -/

@[local step]
theorem common.const_time_slices_equal_local.spec
    (a b : Slice U8) (h_len : a.length = b.length) :
    common.const_time_slices_equal a b
    ⦃ (result : Bool) =>
      result = true ↔ a.val = b.val ⦄ := by
  apply WP.spec_mono (symcrust.const_time_slices_equal.spec a b h_len)
  intro r h; exact h

/-! ## `wfPrivateSeed` — top of the wf-predicate trio

Strictest of three monotone-stronger wf-predicates for a runtime
`mlkem.key.Key` (`wfEncapKey ⟸ wfDecapKey ⟸ wfPrivateSeed`).
Defined here (rather than alongside `wfEncapKey`/`wfDecapKey` in
`Sampling/ExpandMatrix.lean`) because its FC fields name
`K_PKE.KeyGen`, which lives in the spec layer imported by this
file via `Properties.MLKEM.Basic`.

Established when a `PrivateSeed` blob is loaded (or by
`key_generate`).  Adds, on top of `wfDecapKey`:

* `has_private_seed = true`;
* `fc_encaps` / `fc_keys`: the key state literally is the spec-level
  output of `K_PKE.KeyGen p (private_seed.toSpec)`.

Consumed by `mlkem.key_generate.spec` to produce the `RandomTape`
witness, and is the content piece of the PrivateSeed arm of
`key_set_value.spec`. -/

structure wfPrivateSeed
    (self : mlkem.key.Key) (p : ParameterSet) : Prop extends wfDecapKey self p where
  /-- Private-seed material is present (set to `true` by
      `key_set_value(PrivateSeed)` / `key_generate`). -/
  has_private_seed : self.has_private_seed = true
  /-- FC equality on the encapsulation half: the encapsulation-key
      view equals `K_PKE.KeyGen(d).1`, the spec-level output. -/
  fc_encaps : encapsulationKey self p =
              (K_PKE.KeyGen p self.private_seed.toSpec).1
  /-- FC equality on the decapsulation half: the byte-encoded `ŝ`
      slot equals `K_PKE.KeyGen(d).2`, the spec-level dkPKE output. -/
  fc_keys : keySEncoded self p =
            (K_PKE.KeyGen p self.private_seed.toSpec).2

/-! ### Ordering theorems for the wf-predicate trio

The three structures form a monotone-stronger chain.  Each
upcast is a one-line structural projection generated by the
`extends` mechanism, exposed here as named theorems so callers
can refer to them by name. -/

/-- Every decapsulation key is an encapsulation key (structural
projection). -/
theorem wfEncapKey_of_wfDecapKey
    {self : mlkem.key.Key} {p : ParameterSet}
    (h : wfDecapKey self p) : wfEncapKey self p :=
  wfDecapKey.towfEncapKey h

/-- Every private-seed-loaded key is a decapsulation key (structural
projection).  Composed with `wfEncapKey_of_wfDecapKey` it also
yields `wfEncapKey self p` from a `wfPrivateSeed self p`. -/
theorem wfDecapKey_of_wfPrivateSeed
    {self : mlkem.key.Key} {p : ParameterSet}
    (h : wfPrivateSeed self p) : wfDecapKey self p :=
  wfPrivateSeed.towfDecapKey h

/-- Convenience composition: every private-seed-loaded key is an
encapsulation key. -/
theorem wfEncapKey_of_wfPrivateSeed
    {self : mlkem.key.Key} {p : ParameterSet}
    (h : wfPrivateSeed self p) : wfEncapKey self p :=
  wfEncapKey_of_wfDecapKey (wfDecapKey_of_wfPrivateSeed h)

/-! ## Format-parametric key view (`Key.toSpec`)

`pk_mlkem_key.toSpec format params` is the spec-level byte view of the
runtime key at the requested `format`, used uniformly in
`key_set_value.spec`, `key_get_value.spec`, and the documentation. -/

/-- Format-parametric byte view of a runtime `Key`:

* `.PrivateSeed`      → the 64-byte seed `d ‖ z`
* `.EncapsulationKey` → `encapsulationKey self params`
* `.DecapsulationKey` → `decapsulationKey self params`

The result type's length is `format.length params`
(`Basic/Params.lean`).  Use this form in the format-parametric specs;
in format-monomorphic specs prefer the direct `Key.toEncapKey` /
`Key.toDecapKey` abbrevs. -/
@[irreducible] noncomputable def _root_.symcrust.mlkem.key.Key.toSpec
    (self : mlkem.key.Key) (format : mlkem.key.Format) (params : ParameterSet) :
    𝔹 (format.length params) :=
  match format with
  | .PrivateSeed       =>
      (Aeneas.Std.Array.toSpec self.private_seed ‖
       Aeneas.Std.Array.toSpec self.private_random)
  | .EncapsulationKey  => encapsulationKey self params
  | .DecapsulationKey  => decapsulationKey self params

/-- Equation lemma for `Key.toSpec` at `.PrivateSeed`.  Use via explicit
`rw [Key.toSpec_PrivateSeed]` or `simp only [Key.toSpec_PrivateSeed]`;
NOT marked `@[simp]` because indiscriminate firing during `step*`-driven
WP elaboration is expensive. -/
theorem Key.toSpec_PrivateSeed
    (self : mlkem.key.Key) (params : ParameterSet) :
    self.toSpec .PrivateSeed params =
      (Aeneas.Std.Array.toSpec self.private_seed ‖
       Aeneas.Std.Array.toSpec self.private_random) := by
  unfold _root_.symcrust.mlkem.key.Key.toSpec; rfl

/-- Equation lemma for `Key.toSpec` at `.EncapsulationKey`. -/
theorem Key.toSpec_EncapsulationKey
    (self : mlkem.key.Key) (params : ParameterSet) :
    self.toSpec .EncapsulationKey params = encapsulationKey self params := by
  unfold _root_.symcrust.mlkem.key.Key.toSpec; rfl

/-- Equation lemma for `Key.toSpec` at `.DecapsulationKey`. -/
theorem Key.toSpec_DecapsulationKey
    (self : mlkem.key.Key) (params : ParameterSet) :
    self.toSpec .DecapsulationKey params = decapsulationKey self params := by
  unfold _root_.symcrust.mlkem.key.Key.toSpec; rfl

/-! ## Format-parametric wf predicate (`wfKeyFormat`)

`wfKeyFormat self format params` selects the right wf-witness for the
runtime key given the format the caller intends to expose.  Used as
a uniform precondition on `key_get_value.spec` and as a uniform
postcondition on `key_set_value.spec`. -/

/-- Format-parametric wf-predicate selector:

* `.PrivateSeed`      → `wfPrivateSeed self params`
* `.EncapsulationKey` → `wfEncapKey   self params`
* `.DecapsulationKey` → `wfDecapKey   self params`

The three branches form the monotone-stronger chain
`wfEncapKey ⟸ wfDecapKey ⟸ wfPrivateSeed`; consumers project to the
weaker forms with the `wfEncapKey_of_wfDecapKey` /
`wfDecapKey_of_wfPrivateSeed` lemmas above. -/
def wfKeyFormat
    (self : mlkem.key.Key) (format : mlkem.key.Format) (params : ParameterSet) : Prop :=
  match format with
  | .PrivateSeed       => wfPrivateSeed self params
  | .EncapsulationKey  => wfEncapKey   self params
  | .DecapsulationKey  => wfDecapKey   self params

/-- Generic slice-concatenation identity used by the encapsulationKey
proof.  Splitting it out keeps the kernel from re-elaborating it inline
at every call site. -/
private theorem slice_concat_eq_self {α : Type*} {m n : ℕ}
    (v : Vector α (m + n)) :
    slice v 0 m (by grind) ‖ slice v m n (by grind) = v := by
  apply Vector.ext
  intro i hi
  show ((_ : Vector α m) ++ (_ : Vector α n))[i] = _
  rw [Vector.getElem_append]
  simp only [slice, Vector.getElem_ofFn]
  split_ifs with h
  · simp
  · fcongr 1; scalar_tac

/-- A slice `s` of length `m + n` decomposes as the concatenation of its
two `toSpecWindow` projections.  Used to bridge per-field equalities
(`prefix_field = pb_src.toSpecWindow 0 m _`, `suffix_field =
pb_src.toSpecWindow m n _`) to the full `toSpec` equality on
`encapsulationKey = prefix_field ‖ suffix_field`. -/
theorem slice_toSpec_eq_concat2
    (s : Slice U8) {m n : ℕ} (h : s.length = m + n)
    (h0 : 0 + m ≤ s.length) (h1 : m + n ≤ s.length) :
    s.toSpec (m + n) h =
      (s.toSpecWindow 0 m h0 ++ s.toSpecWindow m n h1) := by
  apply Vector.ext
  intro i hi
  show (sliceToSpecBytes s (m + n) h)[i] =
    ((_ : 𝔹 m) ++ (_ : 𝔹 n))[i]
  rw [Vector.getElem_append]
  unfold sliceToSpecBytes
  simp only [Slice.toSpecWindow, sliceWindowToSpecBytes, Vector.getElem_ofFn]
  split_ifs with hlt
  · simp
  · have hsub : m + (i - m) = i := by grind
    simp [hsub]

/-- The encapsulationKey only depends on the `encoded_t` and `public_seed`
fields of the key; in particular it is invariant under flipping the
`has_private_seed` / `has_private_key` booleans. -/
theorem encapsulationKey_struct_upd_flags
    (k : mlkem.key.Key) (params : ParameterSet) (b1 b2 : Bool) :
    encapsulationKey { k with has_private_seed := b1, has_private_key := b2 } params
    = encapsulationKey k params := rfl

/-- As `encapsulationKey_struct_upd_flags`, plus an override of
`private_random` — used by `ksv_decap_after_prep`. -/
theorem encapsulationKey_struct_upd_full
    (k : mlkem.key.Key) (params : ParameterSet) (b1 b2 : Bool)
    (pr : Std.Array U8 32#usize) :
    encapsulationKey { k with has_private_seed := b1, has_private_key := b2,
                              private_random := pr } params
    = encapsulationKey k params := rfl

/-- Bridge `sliceWindowToSpecBytes` from a sub-slice prefix back to the
backing slice when the sub-slice equals `pb.slice 0 i8`.  Used by
`ksv_decap_decode_s` and similar phases that wrap
`vector_decode_and_decompress` over a prefix window. -/
private theorem sliceWindowToSpecBytes_of_slice_prefix
    (pb : Slice U8) (s : Slice U8) (i8 off n : ℕ)
    (h_s : (↑s : List U8) = List.slice 0 i8 ↑pb)
    (h_i8 : i8 ≤ pb.length)
    (h_bound_s : off + n ≤ s.length)
    (h_bound_off : off + n ≤ i8)
    (h_bound_pb : off + n ≤ pb.length) :
    sliceWindowToSpecBytes s off n h_bound_s =
    sliceWindowToSpecBytes pb off n h_bound_pb := by
  unfold sliceWindowToSpecBytes
  apply Vector.ext
  intro i hi
  simp only [Vector.getElem_ofFn]
  have h_idx : off + i < i8 := by scalar_tac
  have h_get : (↑s : List U8)[off + i] = (↑pb : List U8)[off + i] := by
    simp_lists [h_s]
  rw [h_get]

/-- Byte-bridge for `ksv_decap_decode_t_prep` / `ksv_encap_decode_t_prep`:
when `s5 = pb_src[i8..i9]` is copied into `encoded_t[0..cb]` via
`setSlice!`, the resulting array at index `j < cb` reads from
`pb_src[i8 + j]`. -/
private theorem setSlice_eq_pb_byte
    (encoded_t : List U8) (s5 pb_src : List U8) (i8 i9 cb : ℕ)
    (h_s5_val : s5 = List.slice i8 i9 pb_src)
    (h_s5_len : s5.length = cb)
    (h_i9 : i9 = i8 + cb)
    (h_cb_pb : i8 + cb ≤ pb_src.length)
    (h_cb_enc : cb ≤ encoded_t.length)
    (j : ℕ) (h_j : j < cb) :
    (encoded_t.setSlice! 0 s5)[j]'(by simp [List.length_setSlice!]; scalar_tac) =
    pb_src[i8 + j]'(by scalar_tac) := by
  have h_lhs := List.getElem_setSlice!_middle encoded_t s5 0 j
                 ⟨by scalar_tac, by scalar_tac, by scalar_tac⟩
  rw [h_lhs]
  simp only [Nat.sub_zero]
  simp_lists [h_s5_val]


/-- Packaging helper: assemble `wfPrivateSeed pk1 params` from the
raw posts of `key_expand_from_private_seed.spec` together with the
key-load flags and base layout invariant.

The helper takes the seed value `d : 𝔹 32` as an explicit parameter
and all four FC posts in the exact form that `step*` produces them
(now that `keyEncodedTPrefix` and `keySEncoded` carry types matching
`K_PKE.KeyGen p d` outputs, all four posts are plain `=`).  The
caller passes posts 8–11 directly, plus a `h_priv_pres` bridge
linking `pk1.private_seed` to the seed value `d` that appears in
those posts.

Keeping `d` opaque (not unifying through it) and not asking the
kernel to bridge between `Vector.ofFn`- and `arrayToSpecBytes`-forms
at the call site is what keeps elaboration of the call site fast: it
sidesteps the whnf antipattern documented in plan.md ("Detecting
whnf-timeout antipatterns"). -/
private theorem wfPrivateSeed_of_keyExpand_posts
    {params : ParameterSet}
    {pk1 : mlkem.key.Key}
    {d : 𝔹 32}
    (h_wf : wfKey pk1 params)
    (h_has_priv_seed : pk1.has_private_seed = true)
    (h_has_priv_key  : pk1.has_private_key = true)
    (h_priv_pres : pk1.private_seed.toSpec = d)
    (h_pub : pk1.public_seed.toSpec =
             slice (K_PKE.KeyGen params d).1 (384 * (k params : ℕ)) 32 (by grind))
    (h_enc : keyEncodedTPrefix pk1 params =
             slice (K_PKE.KeyGen params d).1 0 (384 * (k params : ℕ)) (by grind))
    (h_s   : keySEncoded pk1 params = (K_PKE.KeyGen params d).2)
    (h_hash : pk1.encaps_key_hash.toSpec =
              Spec.SHA3.sha3_256 (K_PKE.KeyGen params d).1)
    /- Matrix witness — produced by `key_expand_from_private_seed.spec`
    via `keyExpand.Inv4 → Inv2`: each `data[row*k+col]` slot encodes
    `SampleNTT(expandAEntrySeed ρ col row)` where `ρ = (G(d‖k)).1`. -/
    (h_matrix : ∀ (row col : ℕ) (_h_kpos : row < (k params : ℕ) ∧ col < (k params : ℕ)),
      toPoly (pk1.data[row * (k params : ℕ) + col]'(by
        have h1 : pk1.data.val.length = 24 := pk1.data.property
        have h_kpos := k_le_4 params
        have h_ksq := k_sq_plus_2k_le_24 params
        scalar_tac)) =
      MLKEM.SampleNTT
        (expandAEntrySeed (G (d ‖ #v[((k params : ℕ) : Byte)])).1 col row))
    /- Byte-form witness — produced by `key_expand_from_private_seed.spec`'s
    `keyExpand.Inv4` 9th conjunct: `keyEncodedTPrefix` equals the canonical
    12-bit `ByteEncode` of `keyT pk1`. -/
    (h_byteForm : keyEncodedTPrefix pk1 params =
      Vector.cast (n := (k params : ℕ) * (32 * 12)) (m := 384 * (k params : ℕ))
        (by have := polyVector_byteEncode_size_cast (n := k params) 12; omega)
        (MLKEM.PolyVector.ByteEncode 12 (keyT pk1 params) ⟨by omega, by omega⟩)) :
    wfPrivateSeed pk1 params := by
  /- First, derive the public-key shape (hash_pinned).  hash_pinned wants
     `encaps_key_hash.toSpec = SHA3 (encapsulationKey self params)`; we
     have the analogous equation pinned to `K_PKE.KeyGen(d).1`, and the
     encapsulation-key view collapses to the concatenation of the encoded
     prefix and the public-seed window. -/
  have h_fc_encaps : encapsulationKey pk1 params =
      (K_PKE.KeyGen params d).1 := by
    unfold encapsulationKey
    rw [h_enc, h_pub]
    exact slice_concat_eq_self _
  have h_hash_pinned : keyHashPinned pk1 params := by
    show pk1.encaps_key_hash.toSpec =
      Spec.SHA3.sha3_256
        (keyEncodedTPrefix pk1 params ‖ pk1.public_seed.toSpec)
    rw [h_hash, ← h_fc_encaps]
    rfl
  /- Matrix witness in `wfEncapKey`'s shape: `keyAHat[i,j] =
     SampleNTT (public_seed.toSpec ‖ #v[i] ‖ #v[j])`. -/
  have h_matrix' : ∀ (i j : ℕ)
      (hi : i < (k params : ℕ)) (hj : j < (k params : ℕ)),
      Bridges.keyAHat pk1 params ⟨i, hi⟩ ⟨j, hj⟩ =
        MLKEM.SampleNTT
          (pk1.public_seed.toSpec ‖
            #v[(i : Byte)] ‖ #v[(j : Byte)]) := by
    intro i j hi hj
    have h_seed_eq : pk1.public_seed.toSpec =
        (G (d ‖ #v[((k params : ℕ) : Byte)])).1 := by
      rw [h_pub]; exact KPKE_fst_suffix_eq_rho params d
    rw [h_seed_eq]
    have hm := h_matrix i j ⟨hi, hj⟩
    simp only [expandAEntrySeed] at hm
    show toPoly _ = _
    exact hm
  /- Now assemble the `wfPrivateSeed` structure.  The three nested
     `wf*` records inherit via `extends`; the FC fields wrap the
     `private_seed.toSpec` bridge so the outer caller sees a
     `(K_PKE.KeyGen p (private_seed.toSpec))`-pinned post. -/
  refine
    { towfDecapKey :=
        { towfEncapKey :=
            { towfKey := h_wf
              hash_pinned := h_hash_pinned
              byte_form_t := ⟨keyT pk1 params, h_byteForm, rfl⟩
              matrix_form_a := h_matrix' }
          has_private_key := h_has_priv_key }
      has_private_seed := h_has_priv_seed
      fc_encaps := ?_
      fc_keys := ?_ }
  · rw [h_priv_pres]; exact h_fc_encaps
  · rw [h_priv_pres]; exact h_s

/-- **Helper for closing `wfEncapKey.byte_form_t`** —
takes the per-row decode + canonicity facts (in the shape produced
by `vector_decode_and_decompress.spec`) plus the data/encoded_t
bridges, and produces the FIPS 203 byte-form commitment
`keyEncodedTPrefix self p = (ByteEncode 12 (keyT self p)).cast _`.

Used at the `byte_form_t` field of `wfEncapKey` in
`ksv_encap_after_prep.spec` and `ksv_decap_after_prep.spec`. -/
theorem byte_form_t_bridge
    {params : ParameterSet} (key : mlkem.key.Key)
    (t : Slice PolyElement) (err : Slice U8)
    (h_t_len : t.length = (k params : ℕ))
    (h_err_len : err.length = 384 * (k params : ℕ))
    (h_data_t : ∀ (j : ℕ) (h_j : j < (k params : ℕ)),
        key.data.val[matrixLen params + j]'(by
          have hl : key.data.val.length = 24 := key.data.property
          have := k_sq_plus_2k_le_24 params
          unfold matrixLen; grind) =
        t.val[j]'(by
          rw [show t.val.length = t.length from rfl, h_t_len]; exact h_j))
    (h_enc_err : ∀ (i : ℕ) (h_i : i < 384 * (k params : ℕ)),
        key.encoded_t.val[i]'(by
          have hl : key.encoded_t.val.length = 1536 := key.encoded_t.property
          have hk : (k params : ℕ) ≤ 4 := k_le_4 params; grind) =
        err.val[i]'(by
          rw [show err.val.length = err.length from rfl, h_err_len]; exact h_i))
    (h_row : ∀ (j : ℕ) (h_j : j < (k params : ℕ)),
        ∃ (h_window : (j + 1) * (32 * 12) ≤ err.length),
          toPoly (t.val[j]'(by
              rw [show t.val.length = t.length from rfl, h_t_len]; exact h_j))
            = decodeDecompressPoly 12
                (sliceWindowToSpecBytes err (j * (32 * 12)) (32 * 12)
                  (Nat.add_one_mul _ _ ▸ h_window))
                ⟨by decide, by decide⟩ ∧
          (∀ (i : ℕ) (_h_i : i < 256),
            dBitSegment 12
                (sliceWindowToSpecBytes err (j * (32 * 12)) (32 * 12)
                  (Nat.add_one_mul _ _ ▸ h_window))
                i < MLKEM.m 12)) :
    keyEncodedTPrefix key params =
      (MLKEM.PolyVector.ByteEncode 12 (keyT key params)).cast
        (polyVector_byteEncode_size_cast 12) := by
  have hk_le : (k params : ℕ) ≤ 4 := k_le_4 params
  -- Step 1: window-equality bridge between `Spec.slice (keyEncodedTPrefix ..)`
  -- and `sliceWindowToSpecBytes err`.
  have h_window_eq : ∀ (j : ℕ) (_h_j : j < (k params : ℕ))
      (h_b1 : 32 * 12 * j + 32 * 12 ≤ 384 * (k params : ℕ))
      (h_b2 : j * (32 * 12) + 32 * 12 ≤ err.length),
      Spec.slice (keyEncodedTPrefix key params) (32 * 12 * j) (32 * 12) h_b1 =
      sliceWindowToSpecBytes err (j * (32 * 12)) (32 * 12) h_b2 := by
    intro j _h_j h_b1 _h_b2
    apply Vector.ext
    intro l hl
    simp only [Spec.slice, sliceWindowToSpecBytes, keyEncodedTPrefix,
               Vector.getElem_ofFn]
    have h_idx_eq : 32 * 12 * j + l = j * (32 * 12) + l := by ring
    have h_idx_lt : 32 * 12 * j + l < 384 * (k params : ℕ) := by
      have : 32 * 12 * j + l < 32 * 12 * j + 32 * 12 := by omega
      omega
    rw [h_enc_err (32 * 12 * j + l) h_idx_lt,
        getElem_congr_idx (c := (↑err : List U8)) h_idx_eq]
    simp
  -- Step 2: decodeDecompressPoly at d=12 reduces to MLKEM.ByteDecode 12.
  have h_decode12 : ∀ (B : 𝔹 (32 * 12)),
      decodeDecompressPoly 12 B ⟨by decide, by decide⟩ =
      MLKEM.ByteDecode B (d := 12) ⟨by decide, by decide⟩ := by
    intro B
    unfold decodeDecompressPoly
    simp only [show ¬ (12 : ℕ) < 12 from by omega, dif_neg, not_false_iff]
  -- Step 3: keyT key params = ByteDecode 12 (keyEncodedTPrefix key params).
  have h_kT_eq : keyT key params =
      MLKEM.PolyVector.ByteDecode 12 (keyEncodedTPrefix key params)
        ⟨by decide, by decide⟩ := by
    apply Vector.ext
    intro j hj
    simp only [keyT, Vector.getElem_ofFn]
    have h_data := h_data_t j hj
    obtain ⟨h_window, h_decode_eq, _⟩ := h_row j hj
    have h_b1 : 32 * 12 * j + 32 * 12 ≤ 384 * (k params : ℕ) := by
      have h_mul : (j + 1) * (32 * 12) ≤ (k params : ℕ) * (32 * 12) :=
        Nat.mul_le_mul_right _ hj
      have h_lhs : (j + 1) * (32 * 12) = 32 * 12 * j + 32 * 12 := by ring
      have h_rhs : (k params : ℕ) * (32 * 12) = 384 * (k params : ℕ) := by ring
      omega
    have h_b2 : j * (32 * 12) + 32 * 12 ≤ err.length := by
      have h_mul : (j + 1) * (32 * 12) ≤ err.length := h_window
      have h_lhs : (j + 1) * (32 * 12) = j * (32 * 12) + 32 * 12 := by ring
      omega
    have h_we := h_window_eq j hj h_b1 h_b2
    -- LHS toPoly key.data[tOffset+j] → toPoly t.val[j] (h_data, tOffset=matrixLen reducibly).
    -- t.val[j] decode → decodeDecompressPoly window → MLKEM.ByteDecode (h_decode12)
    -- → MLKEM.ByteDecode of slice via h_we (rev).
    rw [getElem_congr_idx (c := key.data.val)
          (show tOffset params + j = matrixLen params + j from rfl),
        h_data, h_decode_eq, h_decode12, ← h_we]
    -- Now both sides should be `MLKEM.ByteDecode (slice ..)`; unfold RHS PolyVector.
    have h_unfold : (MLKEM.PolyVector.ByteDecode 12 (keyEncodedTPrefix key params)
                      ⟨by decide, by decide⟩)[j]'hj =
        MLKEM.ByteDecode
          (Spec.slice (keyEncodedTPrefix key params) (32 * 12 * j) (32 * 12) h_b1)
          (d := 12) (by decide) := by
      unfold MLKEM.PolyVector.ByteDecode
      exact Vector.getElem_ofFn hj
    exact h_unfold.symm
  -- Step 4: apply the canonical bridge.
  have h_canon : ∀ (j : ℕ) (h_j : j < (k params : ℕ)) (i : ℕ) (_h_i : i < 256),
      dBitSegment 12
          (Spec.slice (keyEncodedTPrefix key params) (32 * 12 * j) (32 * 12)
            (by
              have h_mul : (j + 1) * (32 * 12) ≤ (k params : ℕ) * (32 * 12) :=
                Nat.mul_le_mul_right _ h_j
              have h_lhs : (j + 1) * (32 * 12) = 32 * 12 * j + 32 * 12 := by ring
              have h_rhs : (k params : ℕ) * (32 * 12) = 384 * (k params : ℕ) := by
                ring
              have h_le := MLKEM.Bounds.poly_vec_decode_idx_le 12 j h_j
              omega))
          i < MLKEM.m 12 := by
    intro j h_j i h_i
    obtain ⟨h_window, _, h_can⟩ := h_row j h_j
    have h_can_i := h_can i h_i
    have h_b1 : 32 * 12 * j + 32 * 12 ≤ 384 * (k params : ℕ) := by
      have h_mul : (j + 1) * (32 * 12) ≤ (k params : ℕ) * (32 * 12) :=
        Nat.mul_le_mul_right _ h_j
      have h_lhs : (j + 1) * (32 * 12) = 32 * 12 * j + 32 * 12 := by ring
      have h_rhs : (k params : ℕ) * (32 * 12) = 384 * (k params : ℕ) := by ring
      omega
    have h_b2 : j * (32 * 12) + 32 * 12 ≤ err.length := by
      have h_mul : (j + 1) * (32 * 12) ≤ err.length := h_window
      have h_lhs : (j + 1) * (32 * 12) = j * (32 * 12) + 32 * 12 := by ring
      omega
    have h_we := h_window_eq j h_j h_b1 h_b2
    rw [h_we]
    exact h_can_i
  rw [h_kT_eq]
  exact (polyVector_byteEncode_byteDecode_canonical_eq 12
          ⟨by decide, by decide⟩ (keyEncodedTPrefix key params) h_canon).symm

/-- **Helper for the s-prefix FC equality** — the `ŝ`-half analogue of
`byte_form_t_bridge`.

Given the s-slot data content (`key.data[sOffset + j] = s.val[j]`) and the
per-row decode + canonicity facts (in the shape produced by
`vector_decode_and_decompress.spec`), produces the full FC equality
`keySEncoded key params = pb_src.toSpecWindow 0 (384·k) _`.

Unlike the t-side (which owns a raw `encoded_t` byte field copied verbatim
from the blob), the runtime key stores `ŝ` only as decoded poly slots.
`keySEncoded` is *defined* as `(ByteEncode 12 (keyS_std key)).cast`, so the
FC equality is exactly the canonical `ByteEncode ∘ ByteDecode` round-trip on
the s-window (`polyVector_byteEncode_byteDecode_canonical_eq 12`), justified
by the canonicity guaranteed on the `NoError` arm. -/
theorem keySEncoded_window_bridge
    {params : ParameterSet} (key : mlkem.key.Key)
    (s : Slice PolyElement) (pb_src : Slice U8)
    (h_s_len : s.length = (k params : ℕ))
    (h_win : 0 + 384 * (k params : ℕ) ≤ pb_src.length)
    (h_data_s : ∀ (j : ℕ) (h_j : j < (k params : ℕ)),
        key.data.val[sOffset params + j]'(by
          have hl : key.data.val.length = 24 := key.data.property
          have := k_sq_plus_2k_le_24 params
          unfold sOffset matrixLen; grind) =
        s.val[j]'(by
          rw [show s.val.length = s.length from rfl, h_s_len]; exact h_j))
    (h_row : ∀ (j : ℕ) (h_j : j < (k params : ℕ)),
        ∃ (h_window : (j + 1) * (32 * 12) ≤ pb_src.length),
          toPoly (s.val[j]'(by
              rw [show s.val.length = s.length from rfl, h_s_len]; exact h_j))
            = decodeDecompressPoly 12
                (sliceWindowToSpecBytes pb_src (j * (32 * 12)) (32 * 12)
                  (Nat.add_one_mul _ _ ▸ h_window))
                ⟨by decide, by decide⟩ ∧
          (∀ (i : ℕ) (_h_i : i < 256),
            dBitSegment 12
                (sliceWindowToSpecBytes pb_src (j * (32 * 12)) (32 * 12)
                  (Nat.add_one_mul _ _ ▸ h_window))
                i < MLKEM.m 12)) :
    keySEncoded key params = pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win := by
  have hk_le : (k params : ℕ) ≤ 4 := k_le_4 params
  -- Step 1: window-equality bridge between `Spec.slice (pb_src.toSpecWindow 0 (384k))`
  -- and `sliceWindowToSpecBytes pb_src` (both are byte windows of `pb_src`).
  have h_window_eq : ∀ (j : ℕ) (_h_j : j < (k params : ℕ))
      (h_b1 : 32 * 12 * j + 32 * 12 ≤ 384 * (k params : ℕ))
      (h_b2 : j * (32 * 12) + 32 * 12 ≤ pb_src.length),
      Spec.slice (pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win)
          (32 * 12 * j) (32 * 12) h_b1 =
        sliceWindowToSpecBytes pb_src (j * (32 * 12)) (32 * 12) h_b2 := by
    intro j _h_j h_b1 _h_b2
    apply Vector.ext
    intro l hl
    simp only [Spec.slice, Slice.toSpecWindow, sliceWindowToSpecBytes,
               Vector.getElem_ofFn]
    have h_idx_eq : 0 + (32 * 12 * j + l) = j * (32 * 12) + l := by ring
    rw [getElem_congr_idx (c := (↑pb_src : List U8)) h_idx_eq]
  -- Step 2: decodeDecompressPoly at d=12 reduces to MLKEM.ByteDecode 12.
  have h_decode12 : ∀ (B : 𝔹 (32 * 12)),
      decodeDecompressPoly 12 B ⟨by decide, by decide⟩ =
      MLKEM.ByteDecode B (d := 12) ⟨by decide, by decide⟩ := by
    intro B
    unfold decodeDecompressPoly
    simp only [show ¬ (12 : ℕ) < 12 from by omega, dif_neg, not_false_iff]
  -- Step 3: keyS_std key = ByteDecode 12 (pb_src.toSpecWindow 0 (384k)).
  have h_kS_eq : keyS_std key params =
      MLKEM.PolyVector.ByteDecode 12
        (pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win)
        ⟨by decide, by decide⟩ := by
    apply Vector.ext
    intro j hj
    simp only [keyS_std, Vector.getElem_ofFn]
    have h_data := h_data_s j hj
    obtain ⟨h_window, h_decode_eq, _⟩ := h_row j hj
    have h_b1 : 32 * 12 * j + 32 * 12 ≤ 384 * (k params : ℕ) := by
      have h_mul : (j + 1) * (32 * 12) ≤ (k params : ℕ) * (32 * 12) :=
        Nat.mul_le_mul_right _ hj
      have h_lhs : (j + 1) * (32 * 12) = 32 * 12 * j + 32 * 12 := by ring
      have h_rhs : (k params : ℕ) * (32 * 12) = 384 * (k params : ℕ) := by ring
      omega
    have h_b2 : j * (32 * 12) + 32 * 12 ≤ pb_src.length := by
      have h_mul : (j + 1) * (32 * 12) ≤ pb_src.length := h_window
      have h_lhs : (j + 1) * (32 * 12) = j * (32 * 12) + 32 * 12 := by ring
      omega
    have h_we := h_window_eq j hj h_b1 h_b2
    rw [h_data, h_decode_eq, h_decode12, ← h_we]
    have h_unfold : (MLKEM.PolyVector.ByteDecode 12
                      (pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win)
                      ⟨by decide, by decide⟩)[j]'hj =
        MLKEM.ByteDecode
          (Spec.slice (pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win)
            (32 * 12 * j) (32 * 12) h_b1)
          (d := 12) (by decide) := by
      unfold MLKEM.PolyVector.ByteDecode
      exact Vector.getElem_ofFn hj
    exact h_unfold.symm
  -- Step 4: canonicity of every window, lifted to the sliced form.
  have h_canon : ∀ (j : ℕ) (h_j : j < (k params : ℕ)) (i : ℕ) (_h_i : i < 256),
      dBitSegment 12
          (Spec.slice (pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win)
            (32 * 12 * j) (32 * 12)
            (by
              have h_mul : (j + 1) * (32 * 12) ≤ (k params : ℕ) * (32 * 12) :=
                Nat.mul_le_mul_right _ h_j
              have h_lhs : (j + 1) * (32 * 12) = 32 * 12 * j + 32 * 12 := by ring
              have h_rhs : (k params : ℕ) * (32 * 12) = 384 * (k params : ℕ) := by
                ring
              have h_le := MLKEM.Bounds.poly_vec_decode_idx_le 12 j h_j
              omega))
          i < MLKEM.m 12 := by
    intro j h_j i h_i
    obtain ⟨h_window, _, h_can⟩ := h_row j h_j
    have h_can_i := h_can i h_i
    have h_b1 : 32 * 12 * j + 32 * 12 ≤ 384 * (k params : ℕ) := by
      have h_mul : (j + 1) * (32 * 12) ≤ (k params : ℕ) * (32 * 12) :=
        Nat.mul_le_mul_right _ h_j
      have h_lhs : (j + 1) * (32 * 12) = 32 * 12 * j + 32 * 12 := by ring
      have h_rhs : (k params : ℕ) * (32 * 12) = 384 * (k params : ℕ) := by ring
      omega
    have h_b2 : j * (32 * 12) + 32 * 12 ≤ pb_src.length := by
      have h_mul : (j + 1) * (32 * 12) ≤ pb_src.length := h_window
      have h_lhs : (j + 1) * (32 * 12) = j * (32 * 12) + 32 * 12 := by ring
      omega
    have h_we := h_window_eq j h_j h_b1 h_b2
    rw [h_we]
    exact h_can_i
  -- Assemble: keySEncoded is (ByteEncode 12 (keyS_std)).cast; apply the round-trip.
  unfold keySEncoded
  rw [h_kS_eq]
  exact polyVector_byteEncode_byteDecode_canonical_eq 12
          ⟨by decide, by decide⟩
          (pb_src.toSpecWindow 0 (384 * (k params : ℕ)) h_win) h_canon

/-! ## `#decompose` cascade for `key_set_value`

`mlkem.key_set_value` is a 227-bind dispatcher.  Anatomy:

  5 prefix binds (incl. `cb_encoded_vector`) +
  `if i2 != 0 then InvalidArgument else
     let i3 := flags & FLAG_KEY_NO_FIPS
     if i3 = 0 then  -- FIPS-enforced path
       let i4 := flags & FLAG_KEY_MINIMAL_VALIDATION
       if i4 != 0 then InvalidArgument else <try_new_box + match r + match format>
     else            -- FIPS-skipped path
       <try_new_box + match r + match format>`

The two `match format` blocks (PrivateSeed | EncapsulationKey | DecapsulationKey)
are **definitionally equal** (the FIPS distinction is in the OUTER cascade); we
exploit `#decompose`'s name-reuse behavior — when a sub-expression matches an
already-defined helper, the second invocation folds to the existing def — to
extract both `match format` blocks to a single set of leaf helpers
(`ksv_priv` / `ksv_decap` / `ksv_encap`), no rfl bridges needed.

Each cascade level peels one guard / let / branch.  Multi-clause is used
wherever peer extractions are possible (e.g., 2-way FIPS/noFIPS branch split,
3-way format-arm split).
-/

set_option maxHeartbeats 1000000 in
#decompose mlkem.key_set_value mlkem.key_set_value.fold
  letRange 0 5 => ksv_prefix
  letRange 1 1 => ksv_guard_i2

#decompose ksv_guard_i2 ksv_guard_i2.fold
  branch 1 full => ksv_modes_outer

#decompose ksv_modes_outer ksv_modes_outer.fold
  letRange 1 1 => ksv_dispatch_i3

#decompose ksv_dispatch_i3 ksv_dispatch_i3.fold
  branch 0 full => ksv_fips_path
  branch 1 full => ksv_nofips_path

-- FIPS path peels two extra guards (i4 MINIMAL_VALIDATION + try_new_box).
#decompose ksv_fips_path ksv_fips_path.fold
  letRange 1 1 => ksv_fips_guard_i4

#decompose ksv_fips_guard_i4 ksv_fips_guard_i4.fold
  branch 1 full => ksv_fips_validated

#decompose ksv_fips_validated ksv_fips_validated.fold
  letRange 1 1 => ksv_fips_match_r

#decompose ksv_fips_match_r ksv_fips_match_r.fold
  branch 0 full => ksv_fips_match_format

#decompose ksv_fips_match_format ksv_fips_match_format.fold
  branch 0 full => ksv_priv
  branch 1 full => ksv_decap
  branch 2 full => ksv_encap

-- noFIPS path peels one guard (try_new_box).
#decompose ksv_nofips_path ksv_nofips_path.fold
  letRange 1 1 => ksv_nofips_match_r

#decompose ksv_nofips_match_r ksv_nofips_match_r.fold
  branch 0 full => ksv_nofips_match_format

-- Reuses leaf names from FIPS extraction above; #decompose's name-reuse
-- behavior folds to the already-defined `ksv_priv` / `ksv_decap` / `ksv_encap`
-- (the FIPS check is OUTER to the format dispatch, so the arms match).
#decompose ksv_nofips_match_format ksv_nofips_match_format.fold
  branch 0 full => ksv_priv
  branch 1 full => ksv_decap
  branch 2 full => ksv_encap

/-! ### Leaf splits (PRIV / DECAP / ENCAP) -/

-- PRIV leaf: 40 binds = lencheck (2) + lendispatch (if-else) + body (18 binds).
#decompose ksv_priv ksv_priv.fold
  letRange 0 2 => ksv_priv_lencheck
  letRange 1 1 => ksv_priv_lendispatch

#decompose ksv_priv_lendispatch ksv_priv_lendispatch.fold
  branch 1 full => ksv_priv_body

-- DECAP leaf: 95 binds, 3 nested early-return guards.  Collapsed cascade:
--   ksv_decap → lencheck + lendispatch
--   ksv_decap_lendispatch → decode_s + branch_b   (was: → body → decode_s + branch_b)
--   ksv_decap_branch_b → decode_t_prep + after_prep (was: → body2 → decode_t_prep + after_prep)
-- Eliminates intermediate composers `ksv_decap_body` and `ksv_decap_body2`.
#decompose ksv_decap ksv_decap.fold
  letRange 0 3 => ksv_decap_lencheck
  letRange 1 1 => ksv_decap_lendispatch

set_option maxHeartbeats 1000000 in
set_option maxRecDepth 4096 in
#decompose ksv_decap_lendispatch ksv_decap_lendispatch.fold
  branch 1 (letRange 0 5) => ksv_decap_decode_s
  branch 1 (letRange 1 1) => ksv_decap_branch_b

-- branch_b's position 7 is a `let-pattern (let (t,encoded_t) := p) + do-block`
-- which #decompose's LCNF view treats as ONE opaque position.  ksv_decap_after_prep
-- contains the decode_t + branch_b1 + branch_b2 + private_random pipeline (~25 binds).
set_option maxHeartbeats 1000000 in
set_option maxRecDepth 4096 in
#decompose ksv_decap_branch_b ksv_decap_branch_b.fold
  branch 1 (letRange 0 7) => ksv_decap_decode_t_prep
  branch 1 (letRange 1 4) => ksv_decap_after_prep

-- ENCAP leaf: 60 binds, ONE early-return guard (on decode_t error).
-- Collapsed:  ksv_encap_lendispatch → decode_t_prep + after_prep
-- (was: → body → decode_t_prep + after_prep).  Eliminates `ksv_encap_body`.
#decompose ksv_encap ksv_encap.fold
  letRange 0 3 => ksv_encap_lencheck
  letRange 1 1 => ksv_encap_lendispatch

set_option maxHeartbeats 1000000 in
set_option maxRecDepth 4096 in
#decompose ksv_encap_lendispatch ksv_encap_lendispatch.fold
  branch 1 (letRange 0 6) => ksv_encap_decode_t_prep
  branch 1 (letRange 1 4) => ksv_encap_after_prep

/-! ## Prefix-helper `@[step]` specs

`ksv_prefix` and `kgv_prefix` extract the common preamble of
`key_set_value` / `key_get_value`: cast `n_rows : U8 → Usize`,
compute `cb_encoded_vector = 384·k`, plus (for ksv) the bit-mask
filter applied to the caller's `flags`.  All purely arithmetic; no
errors reachable. -/

/-- **Spec for `ksv_prefix`** — first 5 binds of `key_set_value`.

Result = `(cb_encoded_vector, allowed_flag_check)`, where
`cb_encoded_vector.val = 384·(k params)` and `allowed_flag_check` is
`flags &&& ~~~ (FLAG_KEY_NO_FIPS ||| FLAG_KEY_MINIMAL_VALIDATION)` —
the value the outer guard tests against `0#u32`.

**Proof outline.**
After `unfold ksv_prefix`:
- `step` casts `n_rows : U8 → Usize` (no overflow: `n_rows.val ≤ 4`).
- `step` with `sizeof_encoded_uncompressed_vector.spec` (precondition
  `i.val ≤ 4`) gives `cb_encoded_vector.val = 384·n_rows.val`.
- Three `step`s on bit-ops are purely U32 (literal `|||` then `~~~`
  then `&&&`); each is a defeq.
- `refine ⟨?_, ?_⟩`: first goal `cb_encoded_vector.val = 384·(k params)`
  by rewriting via `cb_encoded_vector_post + i_post + h_nrows`; second
  goal `r.2 = flags &&& ...` by `rfl` (step left `i2_post : i2 = ...`). -/
@[step]
theorem ksv_prefix.spec
    {params : ParameterSet} (flags : U32) (pk_mlkem_key : mlkem.key.Key)
    (h_wf : wfKey pk_mlkem_key params) :
    ksv_prefix flags pk_mlkem_key
      ⦃ (r : Usize × U32) =>
          r.1.val = 384 * (k params : ℕ) ∧
          r.2 = flags &&& ~~~(mlkem.FLAG_KEY_NO_FIPS ||| mlkem.FLAG_KEY_MINIMAL_VALIDATION) ⦄ := by
  unfold ksv_prefix
  have h_nrows : pk_mlkem_key.params.n_rows.val = (k params : ℕ) :=
    wfInternalParams.n_rows_val (wfKey.params_ok (self := pk_mlkem_key) h_wf)
  have h_nle4 : pk_mlkem_key.params.n_rows.val ≤ 4 := by
    rw [h_nrows]; exact k_le_4 params
  step
  have h_i_le4 : i.val ≤ 4 := by rw [i_post]; scalar_tac
  step*
  refine ⟨?_, ?_⟩
  · scalar_tac
  · -- i2 = flags &&& ~~~(FLAG_KEY_NO_FIPS ||| FLAG_KEY_MINIMAL_VALIDATION)
    apply U32.bv_eq_imp_eq
    simp_all [UScalar.bv_and, UScalar.bv_or, UScalar.bv_not]

/-! ## Length-check helper specs

Each of the six `*_lencheck` helpers computes a `(observed, expected)`
length pair for the corresponding format arm.  No errors reachable.
The composer specs (`ksv_priv`, `ksv_decap`, ..., `kgv_encap`) consume
these specs to translate the i5/i6 mismatch into the high-level
`pb_*.length ≠ <expected>` witness on the `WrongKeySize` arm. -/

/-- **`ksv_priv_lencheck`** — `(pb_src.len, SIZEOF_FORMAT_PRIVATE_SEED = 64)`.

**Proof outline.**
After `unfold ksv_priv_lencheck`: `step` on `Slice.len pb_src`, then
`step` (or `unfold SIZEOF_FORMAT_PRIVATE_SEED; step`) on `2#usize * 32#usize`
(literal, no overflow).  Final pair `(i5, i6) = (pb_src.length, 64)` is
the terminal; `refine ⟨rfl, ?_⟩; scalar_tac`. -/
@[step]
theorem ksv_priv_lencheck.spec (pb_src : Slice U8) :
    ksv_priv_lencheck pb_src
      ⦃ r => r.1.val = pb_src.length ∧ r.2.val = 64 ⦄ := by
  unfold ksv_priv_lencheck mlkem.SIZEOF_FORMAT_PRIVATE_SEED
  step
  refine ⟨by simp [Slice.length], ?_⟩
  scalar_tac

/-- **`ksv_decap_lencheck`** — `(pb_src.len, 2·384·k + 96)`.

**Proof outline.**
After `unfold ksv_decap_lencheck`: 3 binds — `i5 := Slice.len pb_src`
(pure live let), `i6 ← cast n_rows` (no overflow, `n_rows.val ≤ 4`),
`i7 ← sizeof_format_decapsulation_key i6` (precondition `i6.val ≤ 4`).
Spec post: `i7.val = 768·n_rows.val + 96 = 768·(k params) + 96`.
`step*` + `scalar_tac`. -/
@[step]
theorem ksv_decap_lencheck.spec
    {params : ParameterSet} (pb_src : Slice U8) (pk_mlkem_key : mlkem.key.Key)
    (h_wf : wfKey pk_mlkem_key params) :
    ksv_decap_lencheck pb_src pk_mlkem_key
      ⦃ (r : Usize × Usize) =>
          r.1.val = pb_src.length ∧ r.2.val = 768 * (k params : ℕ) + 96 ⦄ := by
  unfold ksv_decap_lencheck
  have h_nrows : pk_mlkem_key.params.n_rows.val = (k params : ℕ) :=
    wfInternalParams.n_rows_val (wfKey.params_ok (self := pk_mlkem_key) h_wf)
  have h_nle4 : pk_mlkem_key.params.n_rows.val ≤ 4 := by
    rw [h_nrows]; exact k_le_4 params
  step
  have h_cast_le4 : r.val ≤ 4 := by rw [r_post]; scalar_tac
  step
  refine ⟨by simp [Slice.length], ?_⟩
  rw [i7_post, r_post]; scalar_tac

/-- **`ksv_encap_lencheck`** — `(pb_src.len, 384·k + 32)`.

**Proof outline.**
Symmetric to `ksv_decap_lencheck` but with `sizeof_format_encapsulation_key`. -/
@[step]
theorem ksv_encap_lencheck.spec
    {params : ParameterSet} (pb_src : Slice U8) (pk_mlkem_key : mlkem.key.Key)
    (h_wf : wfKey pk_mlkem_key params) :
    ksv_encap_lencheck pb_src pk_mlkem_key
      ⦃ (r : Usize × Usize) =>
          r.1.val = pb_src.length ∧ r.2.val = 384 * (k params : ℕ) + 32 ⦄ := by
  unfold ksv_encap_lencheck
  have h_nrows : pk_mlkem_key.params.n_rows.val = (k params : ℕ) :=
    wfInternalParams.n_rows_val (wfKey.params_ok (self := pk_mlkem_key) h_wf)
  have h_nle4 : pk_mlkem_key.params.n_rows.val ≤ 4 := by
    rw [h_nrows]; exact k_le_4 params
  step
  have h_cast_le4 : r.val ≤ 4 := by rw [r_post]; scalar_tac
  step
  refine ⟨by simp [Slice.length], ?_⟩
  rw [i7_post, r_post]; scalar_tac

/-! ## `ksv_*` leaf `@[step]` specs

Strong-FC specs for the leaves of `ksv_priv` / `ksv_decap` / `ksv_encap`
extracted by the `#decompose` cascade above.  Each helper's post
contributes its share of the top-spec `key_set_value.spec` postcondition
for the corresponding format arm — no "compose later" deferral. -/

/-! ### `ksv_priv_body` — PrivateSeed arm content (18 binds)

Inside the `pb_src.length = 64` success branch of `ksv_priv_lendispatch`
(after `try_new_box_default` allocated `p_comp_temps`).  Copies the
32-byte `private_seed` and 32-byte `private_random` from `pb_src`,
sets `has_private_seed = has_private_key = true`, then runs
`key_expand_from_private_seed` to derive ρ, t̂, ŝ, Â^T, and H(ek).

Full FC mirrors the PrivateSeed arm of `mlkem.key_set_value.spec`. -/
@[step]
theorem ksv_priv_body.spec
    {params : ParameterSet}
    (pb_src : Slice U8)
    (pk_mlkem_key : mlkem.key.Key)
    (p_comp_temps : mlkem.ntt.InternalComputationTemporaries)
    (h_wf : wfKey pk_mlkem_key params)
    (h_pas_len : pb_src.length = 64)
    (h_pct_max0 : wfPolyVec p_comp_temps.max_size_vector0.to_slice) :
    ksv_priv_body pb_src pk_mlkem_key p_comp_temps
      ⦃ err key' =>
          /- Universal conjuncts (preserved across every reachable arm —
             unreachable arms are `False`, so any property holds vacuously).
             Pulled outside the `match` so callers obtain them without a
             case-split. -/
          wfKey key' params ∧
          key'.params = pk_mlkem_key.params ∧
          key'.n_rows = pk_mlkem_key.n_rows ∧
          match err with
          | Error.NoError =>
              /- Raw seed bytes copied from `pb_src[0..32]` and
                 `pb_src[32..64]`. -/
              key'.private_seed.toSpec = pb_src.toSpecWindow 0 32 (by simp [h_pas_len]) ∧
              key'.private_random.toSpec = pb_src.toSpecWindow 32 32 (by simp [h_pas_len]) ∧
              /- Flags reflect a fully-populated private key. -/
              key'.has_private_seed = true ∧ key'.has_private_key = true ∧
              /- K_PKE.KeyGen FC triple from `key_expand_from_private_seed`. -/
              wfPrivateSeed key' params
          /- Body is past the length check and past `try_new_box_default`;
             no other failure mode is reachable.  Listing `_ => False`
             forces exhaustiveness on enum growth and asserts unreachability
             at call sites. -/
          | _ => False ⦄ := by
  unfold ksv_priv_body
  step*
  case params => exact params
  case hlen => scalar_tac
  case h_wf =>
    exact ⟨wfKey.params_ok (self := pk_mlkem_key) h_wf,
           wfKey.n_rows_ok (self := pk_mlkem_key) h_wf,
           wfKey.data_wf (self := pk_mlkem_key) h_wf⟩
  step*
  obtain ⟨h_wf', h_params', h_n_rows', h_hps', h_psd', _h_prr'⟩ :=
    pk_mlkem_key1_post1
  refine ⟨h_wf', h_params', h_n_rows', ?_, ?_, h_hps', pk_mlkem_key1_post2, ?_⟩
  · -- private_seed.toSpec = pb_src.toSpecWindow 0 32
    rw [h_psd']
    simp_all [arrayToSpecBytes, sliceWindowToSpecBytes, Aeneas.Std.Array.toSpec]
    rfl
  · -- private_random.toSpec = pb_src.toSpecWindow 32 32
    simp_all [arrayToSpecBytes, sliceWindowToSpecBytes, Aeneas.Std.Array.toSpec]
    apply Vector.ext; intro i hi; simp_lists; symm; exact Vector.getElem_ofFn hi
  · -- wfPrivateSeed pk_mlkem_key1 params
    -- Bridge pk1.private_seed back to the input seed via the KeyInv
    -- `private_seed` projection (`h_psd'`) and `s1_post2`
    -- (`to_slice_mut_back = pk_mlkem_key.private_seed.from_slice`).
    have h_priv_pres :
        pk_mlkem_key1.private_seed.toSpec =
          (to_slice_mut_back s3).toSpec := by
      rw [h_psd', s1_post2]
    exact wfPrivateSeed_of_keyExpand_posts
            h_wf' h_hps' pk_mlkem_key1_post2
            h_priv_pres
            pk_mlkem_key1_post3 pk_mlkem_key1_post7
            pk_mlkem_key1_post5 pk_mlkem_key1_post8
            pk_mlkem_key1_post6 pk_mlkem_key1_post9

/-! ### `ksv_decap_decode_s` — decode 12-bit `s` from `pb_src[0..384k]`

5-bind first phase of `ksv_decap_body`.  Computes `cb`-based bounds,
opens `pk.s_mut` to get `(s1, s_mut_back)`, calls
`vector_decode_and_decompress(pb_src[0..cb], 12, s1)` to produce
`s2 : Slice (PolyElement)` with at most an `InvalidBlob` error
(only failure mode of `vector_decode_and_decompress` at `d = 12`),
and finally derives the early-exit flag `b = (sc_error ≠ NoError)`.

Returns `(i8, s_mut_back, sc_error, s2, b)` — the 5-tuple consumed
by `ksv_decap_branch_b`.  `s_mut_back` and `s2` are threaded into
the no-error branch (`ksv_decap_decode_t_prep`); on `InvalidBlob`
the caller still applies `s_mut_back s2` and propagates the error. -/
@[step]
theorem ksv_decap_decode_s.spec
    {params : ParameterSet}
    (pb_src : Slice U8) (pk_mlkem_key : mlkem.key.Key)
    (cb_encoded_vector : Usize)
    (h_wf : wfKey pk_mlkem_key params)
    (h_cb : cb_encoded_vector.val = 384 * (k params : ℕ))
    (h_pas_len : pb_src.length ≥ cb_encoded_vector.val) :
    ksv_decap_decode_s pb_src pk_mlkem_key cb_encoded_vector
      ⦃ (i8 : Usize) (s_mut_back : Slice PolyElement → mlkem.key.Key)
        (sc_error : common.Error) (s2 : Slice PolyElement) (b : Bool) =>
          /- Universal positional facts (hold across every reachable
             sc_error arm). -/
          i8.val = cb_encoded_vector.val ∧
          b = (sc_error ≠ Error.NoError) ∧
          s2.length = (k params : ℕ) ∧
          /- Universal well-formedness of `s2`: the impl rejects any
             out-of-range coefficient BEFORE the store, so even on
             `InvalidBlob` the decoded slice satisfies `wfPolyVec`
             (previously-written slots passed the check; trailing
             slots retain the input's `wfPoly`).  Available on every
             reachable arm thanks to the strengthened
             `vector_decode_and_decompress.spec`. -/
          (∀ i (_ : i < s2.length), wfPoly s2.val[i]) ∧
          /- Back-closure semantics: `s_mut_back` is the back of
             `s_mut pk_mlkem_key`.  Quantify over any compatible
             replacement slice — caller will instantiate at `s2`
             or `s2` (post-decode) depending on branch. -/
          (∀ (s' : Slice PolyElement)
             (_h_s'_len : s'.length = (k params : ℕ))
             (_h_s'_wf : ∀ i (_ : i < s'.length), wfPoly s'.val[i]),
            wfKey (s_mut_back s') params ∧
            (s_mut_back s').params = pk_mlkem_key.params ∧
            (s_mut_back s').n_rows = pk_mlkem_key.n_rows ∧
            (s_mut_back s').has_private_seed = pk_mlkem_key.has_private_seed ∧
            (s_mut_back s').has_private_key = pk_mlkem_key.has_private_key ∧
            (s_mut_back s').private_seed = pk_mlkem_key.private_seed ∧
            (s_mut_back s').private_random = pk_mlkem_key.private_random ∧
            (s_mut_back s').public_seed = pk_mlkem_key.public_seed ∧
            (s_mut_back s').encoded_t = pk_mlkem_key.encoded_t ∧
            (s_mut_back s').encaps_key_hash = pk_mlkem_key.encaps_key_hash ∧
            /- S-slot read-back: the back-closure writes `s'` into the
               `ŝ` data window `[sOffset, sOffset + k)`.  Threaded from
               `s_mut.spec` so the caller (`ksv_decap_branch_b`) can bridge
               the decoded `s2` to `keySEncoded (s_mut_back s2)`. -/
            (∀ (i : ℕ) (_h_i : i < (k params : ℕ)),
              (s_mut_back s').data.val[sOffset params + i]'(by
                have hl : (s_mut_back s').data.val.length = 24 :=
                  (s_mut_back s').data.property
                have := k_sq_plus_2k_le_24 params
                unfold sOffset matrixLen; grind) =
              s'.val[i]'(by
                rw [show s'.val.length = s'.length from rfl, _h_s'_len];
                exact _h_i))) ∧
          /- Branch on `sc_error` — `vector_decode_and_decompress`
             at `d = 12` can fail only with `InvalidBlob` (the
             12-bit coefficient ≥ q check); body is past length
             dispatch, so no other failure is reachable. -/
          match sc_error with
          | Error.NoError =>
              (∀ i (_ : i < s2.length), wfPoly s2.val[i]) ∧
              (∀ (j : Nat) (h_j : j < s2.length),
                ∃ (h_w : (j + 1) * (32 * 12) ≤ cb_encoded_vector.val),
                  toPoly (s2.val[j]'h_j) =
                    decodeDecompressPoly 12
                      (sliceWindowToSpecBytes pb_src
                        (j * (32 * 12)) (32 * 12)
                        (by have := h_w; have := h_pas_len; scalar_tac))
                      ⟨by decide, by decide⟩ ∧
                  (∀ (i : ℕ) (_h_i : i < 256),
                    dBitSegment 12
                      (sliceWindowToSpecBytes pb_src
                        (j * (32 * 12)) (32 * 12)
                        (by have := h_w; have := h_pas_len; scalar_tac))
                      i < MLKEM.m 12))
          | Error.InvalidBlob => True
          | _ => False ⦄ := by
  unfold ksv_decap_decode_s
  have hk_ge2 := k_ge_2 params
  have hk_le4 := k_le_4 params
  step*
  case h_wf_in => exact s1_post2
  have h_s_len : s.length = cb_encoded_vector.val := by scalar_tac
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · scalar_tac
  · simp [b_post]
  · rw [sc_error_post1, s1_post1]
  · exact sc_error_post2
  · intro s' h_s'_len h_s'_wf
    have := s1_post4 s' h_s'_len h_s'_wf
    -- s_mut.spec's back-closure post returns `KeyInv ∧ algorithm_info ∧
    -- has_private_key ∧ public_seed ∧ encoded_t ∧ encaps_key_hash ∧ ∃…`.
    -- KSV's caller post still wants the full 10-field expansion; destructure
    -- KeyInv for the 6 invariant-tracked fields (wf, params, n_rows,
    -- has_private_seed, private_seed, private_random) and pull the rest
    -- positionally.
    obtain ⟨⟨h_wf, h_params, h_n_rows, h_hps, h_psd, h_prr⟩,
            _h_algo, h_hpk, h_pubs, h_encT, h_hash, h_data⟩ := this
    obtain ⟨_h_dlen, h_readback, _h_frame⟩ := h_data
    exact ⟨h_wf, h_params, h_n_rows, h_hps, h_hpk, h_psd, h_prr,
           h_pubs, h_encT, h_hash, h_readback⟩
  · -- match sc_error post
    match sc_error, sc_error_post3 with
    | .NoError, h_per =>
        refine ⟨?_, ?_⟩
        · intro i hi
          exact sc_error_post2 i hi
        · intro j h_j
          obtain ⟨h_w_s, h_eq, h_canon⟩ := h_per j h_j
          have h_w_pb : (j + 1) * (32 * 12) ≤ cb_encoded_vector.val := h_s_len ▸ h_w_s
          have h_swt :
              sliceWindowToSpecBytes s (j * (32 * 12)) (32 * (12#u32).val)
                (by have : (j+1) * (32 * 12) ≤ s.length := h_w_s; scalar_tac) =
              sliceWindowToSpecBytes pb_src (j * (32 * 12)) (32 * 12)
                (by have := h_pas_len; have := h_s_len; scalar_tac) :=
            sliceWindowToSpecBytes_of_slice_prefix
              pb_src s i8.val (j * (32 * 12)) (32 * 12) s_post1
              (by scalar_tac) _ (by have := h_s_len ▸ h_w_s; scalar_tac) _
          refine ⟨h_w_pb, ?_, ?_⟩
          · rw [h_eq, h_swt]
            rfl
          · intro i hi
            have hc := h_canon i hi
            rw [h_swt] at hc
            exact hc
    | .InvalidBlob, _ => trivial
    | .Unused, h | .WrongKeySize, h | .WrongBlockSize, h | .WrongDataSize, h
    | .WrongNonceSize, h | .WrongTagSize, h | .WrongIterationCount, h
    | .AuthenticationFailure, h | .ExternalFailure, h | .FipsFailure, h
    | .HardwareFailure, h | .NotImplemented, h
    | .BufferTooSmall, h | .MemoryAllocationFailure, h
    | .SignatureVerificationFailure, h | .IncompatibleFormat, h
    | .ValueTooLarge, h | .SessionReplayFailure, h | .InvalidArgument, h
    | .HbsNoOtsKeysLeft, h | .HbsPublicRootMismatch, h => exact h.elim

/-! ### `ksv_decap_decode_t_prep` — prepare encoded_t + open t_encoded_t_mut

7-bind phase between `ksv_decap_decode_s` and `ksv_decap_after_prep`.
Apply `s_mut_back` to the decoded `s2`, then:
  • open `index_mut` on `encoded_t[0..cb]`,
  • copy `pb_src[cb..2·cb]` into the encoded_t window,
  • call `t_encoded_t_mut` on the updated key to expose
    `(t : Slice PolyElement, encoded_t : Array U8 1536)`
    and the back-closure `t_encoded_t_mut_back`.

Returns `(i9 := i8 + cb, (t, encoded_t), t_encoded_t_mut_back)`.
All operations always succeed (no error projection); only `NoError`
is reachable. -/
/-- `ksv_decap_decode_t_prep` is the second leaf of `ksv_decap_body`:
opens the back-closure of `s_mut_back`, copies pb_src[cb..2cb] into the
encoded_t slot, and opens `t_encoded_t_mut`.  This is purely slice
plumbing — no decode error possible.  The wfKey precondition
`h_back_wf` is established by chaining from `ksv_decap_decode_s.spec`. -/
@[step]
theorem ksv_decap_decode_t_prep.spec
    {params : ParameterSet}
    (pb_src : Slice U8) (cb_encoded_vector : Usize) (i8 : Usize)
    (s_mut_back : Slice PolyElement → mlkem.key.Key)
    (s2 : Slice PolyElement)
    (h_cb : cb_encoded_vector.val = 384 * (k params : ℕ))
    (h_i8 : i8.val = cb_encoded_vector.val)
    (h_s2_len : s2.length = (k params : ℕ))
    (h_s2_wf : ∀ i (_ : i < s2.length), wfPoly s2.val[i])
    (h_pas_len : pb_src.length ≥ 2 * cb_encoded_vector.val)
    /- `s_mut_back s2`'s field preservations.  In the call chain this
       is established by `ksv_decap_decode_s.spec` (the back-closure
       conjunct, specialised at `s' := s2`).  Pulled into a single
       precondition so this leaf can be stated locally. -/
    (h_back_wf : wfKey (s_mut_back s2) params) :
    ksv_decap_decode_t_prep pb_src cb_encoded_vector i8 s_mut_back s2
      ⦃ (i9 : Usize)
        (t : Slice PolyElement)
        (encoded_t : Array U8 1536#usize)
        (t_encoded_t_mut_back :
          Slice PolyElement × Array U8 1536#usize → mlkem.key.Key) =>
          i9.val = 2 * cb_encoded_vector.val ∧
          t.length = (k params : ℕ) ∧
          (∀ i (_ : i < t.length), wfPoly t.val[i]) ∧
          /- The encoded_t exposed by `t_encoded_t_mut` is the updated
             array whose first `cb` bytes mirror `pb_src[cb..2·cb]`.
             Other bytes inherit the prior `(s_mut_back s2).encoded_t`
             content; consumers (`after_prep`) only read the first cb. -/
          (∃ (h_len : encoded_t.val.length = 1536),
            (∀ (j : Nat) (h_j : j < cb_encoded_vector.val),
              encoded_t.val[j]'(by simp only [h_len]; have := h_cb; have := k_le_4 params; scalar_tac)
                =
              pb_src.val[i8.val + j]'(by have := h_i8; have := h_pas_len; scalar_tac))) ∧
          /- Back-closure semantics for `t_encoded_t_mut`: returning a
             key whose `(t, encoded_t)` slots are replaced by the
             argument pair, with all other fields preserved from the
             input `(s_mut_back s2)` (mutated encoded_t slot ignored
             — back fully overwrites `encoded_t`). -/
          (∀ (t' : Slice PolyElement) (enc' : Array U8 1536#usize)
             (_h_t'_len : t'.length = (k params : ℕ))
             (_h_t'_wf : ∀ i (_ : i < t'.length), wfPoly t'.val[i]),
            wfKey (t_encoded_t_mut_back (t', enc')) params ∧
            (t_encoded_t_mut_back (t', enc')).params =
              (s_mut_back s2).params ∧
            (t_encoded_t_mut_back (t', enc')).n_rows =
              (s_mut_back s2).n_rows ∧
            (t_encoded_t_mut_back (t', enc')).encoded_t = enc' ∧
            (t_encoded_t_mut_back (t', enc')).private_seed =
              (s_mut_back s2).private_seed ∧
            (t_encoded_t_mut_back (t', enc')).private_random =
              (s_mut_back s2).private_random ∧
            (t_encoded_t_mut_back (t', enc')).public_seed =
              (s_mut_back s2).public_seed ∧
            (t_encoded_t_mut_back (t', enc')).encaps_key_hash =
              (s_mut_back s2).encaps_key_hash ∧
            (t_encoded_t_mut_back (t', enc')).has_private_seed =
              (s_mut_back s2).has_private_seed ∧
            (t_encoded_t_mut_back (t', enc')).has_private_key =
              (s_mut_back s2).has_private_key ∧
            /- T-slot frame: back-fn writes the t-slot
               [matrixLen, matrixLen + k) from `t'.val`.  Exposed in
               setSlice! form (the underlying t_encoded_t_mut.spec's
               native shape) — the byte_form_t use site derives the
               elementwise form via List.getElem_setSlice!_middle. -/
            (t_encoded_t_mut_back (t', enc')).data.val =
              (s_mut_back s2).data.val.setSlice! (matrixLen params) t'.val) ⦄ := by
  unfold ksv_decap_decode_t_prep
  have h_back := h_back_wf
  have h_cb_le : cb_encoded_vector.val ≤ 1536 := by
    have := k_le_4 params; scalar_tac
  step*
  · exact params
  · scalar_tac
  · obtain ⟨a, b, c⟩ := h_back; exact ⟨a, b, c⟩
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · scalar_tac
  · exact t_post1
  · exact t_post2
  · subst t_post3
    refine ⟨?_, ?_⟩
    · simp only [s3_post3, List.length_setSlice!]
      exact (s_mut_back s2).encoded_t.property
    · intro j h_j
      simp only [s3_post3]
      have h_encoded_len : (s_mut_back s2).encoded_t.val.length = 1536 :=
        (s_mut_back s2).encoded_t.property
      have h_s5_len_eq : s5.length = cb_encoded_vector.val := by
        rw [s5_post1]; scalar_tac
      have h_s5_val : (↑s5 : List U8) = List.slice i8.val i9.val ↑pb_src := by
        rw [s5_post2, s4_post1]
      have h_s5_len' : (↑s5 : List U8).length = cb_encoded_vector.val := by
        rw [← Slice.length]; exact h_s5_len_eq
      have h_i9_val : i9.val = i8.val + cb_encoded_vector.val := i9_post
      have h_cb_pb : i8.val + cb_encoded_vector.val ≤ (↑pb_src : List U8).length := by
        have h_pas := h_pas_len
        have h_i8' := h_i8
        have h_eq : pb_src.length = (↑pb_src : List U8).length := rfl
        rw [h_eq] at h_pas
        calc i8.val + cb_encoded_vector.val
            = cb_encoded_vector.val + cb_encoded_vector.val := by rw [h_i8']
          _ = 2 * cb_encoded_vector.val := by ring
          _ ≤ (↑pb_src : List U8).length := h_pas
      have h_cb_enc : cb_encoded_vector.val ≤ (↑(s_mut_back s2).encoded_t : List U8).length := by
        rw [h_encoded_len]; exact h_cb_le
      exact setSlice_eq_pb_byte (↑(s_mut_back s2).encoded_t) (↑s5) (↑pb_src)
              i8.val i9.val cb_encoded_vector.val
              h_s5_val h_s5_len' h_i9_val h_cb_pb h_cb_enc j h_j
  · intro t' enc' h_t'_len h_t'_wf
    -- `t_encoded_t_mut.spec`'s post returns `KeyInv ∧ encoded_t ∧ public_seed ∧
    -- encaps_key_hash ∧ has_private_key ∧ data_frame`, with a back-closure
    -- carrying the `.data.val = setSlice!` data-frame conjunct.  Project
    -- through KeyInv for the 6 invariant-tracked fields and pull the 4
    -- explicit fields out positionally; thread h_data straight through.
    have h_p5 := t_post5 t' enc' h_t'_len h_t'_wf
    obtain ⟨⟨h_wf, h_params, h_n_rows, h_hps, h_psd, h_prr⟩,
            h_encT, h_pubs, h_hash, h_hpk, h_data⟩ := h_p5
    exact ⟨h_wf, h_params, h_n_rows, h_encT, h_psd, h_prr,
           h_pubs, h_hash, h_hps, h_hpk, h_data⟩

/-! ### `ksv_encap_decode_t_prep` — open encoded_t + copy from pb_src + open t_encoded_t_mut

6-bind first phase of `ksv_encap_body`.  Like `ksv_decap_decode_t_prep`
but starts from `pk_mlkem_key` directly (no prior s decode):

  • open `index_mut` on `encoded_t[0..cb]`,
  • compute `i8 := 0 + cb`, slice `pb_src[0..i8]`,
  • copy that into encoded_t window,
  • call `t_encoded_t_mut`.

Returns `(i8, p, t_encoded_t_mut_back)`.  Always succeeds. -/
@[step]
theorem ksv_encap_decode_t_prep.spec
    {params : ParameterSet}
    (pb_src : Slice U8) (pk_mlkem_key : mlkem.key.Key)
    (cb_encoded_vector : Usize)
    (h_wf : wfKey pk_mlkem_key params)
    (h_cb : cb_encoded_vector.val = 384 * (k params : ℕ))
    (h_pas_len : pb_src.length ≥ cb_encoded_vector.val) :
    ksv_encap_decode_t_prep pb_src pk_mlkem_key cb_encoded_vector
      ⦃ (i8 : Usize)
        (t : Slice PolyElement)
        (encoded_t : Array U8 1536#usize)
        (t_encoded_t_mut_back :
          Slice PolyElement × Array U8 1536#usize → mlkem.key.Key) =>
          i8.val = cb_encoded_vector.val ∧
          t.length = (k params : ℕ) ∧
          (∀ i (_ : i < t.length), wfPoly t.val[i]) ∧
          /- encoded_t has been overwritten on `[0..cb)` with the
             leading `cb` bytes of `pb_src`.  Bytes past `cb` retain
             the input key's prior encoded_t content. -/
          (∃ (h_len : encoded_t.val.length = 1536),
            (∀ (j : Nat) (h_j : j < cb_encoded_vector.val),
              encoded_t.val[j]'(by simp only [h_len]; have := h_cb; have := k_le_4 params; scalar_tac)
                =
              pb_src.val[j]'(by have := h_pas_len; scalar_tac))) ∧
          /- Back-closure semantics for `t_encoded_t_mut` —
             reassembles a key whose `(t, encoded_t)` slots are
             replaced by the argument pair and other fields are
             preserved from `pk_mlkem_key`. -/
          (∀ (t' : Slice PolyElement) (enc' : Array U8 1536#usize)
             (_h_t'_len : t'.length = (k params : ℕ))
             (_h_t'_wf : ∀ i (_ : i < t'.length), wfPoly t'.val[i]),
            wfKey (t_encoded_t_mut_back (t', enc')) params ∧
            (t_encoded_t_mut_back (t', enc')).params = pk_mlkem_key.params ∧
            (t_encoded_t_mut_back (t', enc')).n_rows = pk_mlkem_key.n_rows ∧
            (t_encoded_t_mut_back (t', enc')).encoded_t = enc' ∧
            (t_encoded_t_mut_back (t', enc')).private_seed =
              pk_mlkem_key.private_seed ∧
            (t_encoded_t_mut_back (t', enc')).private_random =
              pk_mlkem_key.private_random ∧
            (t_encoded_t_mut_back (t', enc')).public_seed =
              pk_mlkem_key.public_seed ∧
            (t_encoded_t_mut_back (t', enc')).encaps_key_hash =
              pk_mlkem_key.encaps_key_hash ∧
            (t_encoded_t_mut_back (t', enc')).has_private_seed =
              pk_mlkem_key.has_private_seed ∧
            (t_encoded_t_mut_back (t', enc')).has_private_key =
              pk_mlkem_key.has_private_key ∧
            /- T-slot frame: back-fn writes the t-slot
               [matrixLen, matrixLen + k) from `t'.val`.  Exposed in
               setSlice! form (the underlying t_encoded_t_mut.spec's
               native shape) — the byte_form_t use site derives the
               elementwise form via List.getElem_setSlice!_middle. -/
            (t_encoded_t_mut_back (t', enc')).data.val =
              pk_mlkem_key.data.val.setSlice! (matrixLen params) t'.val) ⦄ := by
  unfold ksv_encap_decode_t_prep
  have h_cb_le : cb_encoded_vector.val ≤ 1536 := by
    have := k_le_4 params; scalar_tac
  step*
  case p => exact params
  case _h =>
    exact ⟨wfKey.params_ok (self := pk_mlkem_key) h_wf,
           wfKey.n_rows_ok (self := pk_mlkem_key) h_wf,
           wfKey.data_wf (self := pk_mlkem_key) h_wf⟩
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · scalar_tac
  · exact t_post1
  · exact t_post2
  · subst t_post3
    refine ⟨?_, ?_⟩
    · simp only [s_post3, List.length_setSlice!]
      exact pk_mlkem_key.encoded_t.property
    · intro j h_j
      simp only [s_post3]
      have h_encoded_len : (↑pk_mlkem_key.encoded_t : List U8).length = 1536 :=
        pk_mlkem_key.encoded_t.property
      have h_s2_len_eq : s2.length = cb_encoded_vector.val := by
        rw [s2_post1]; scalar_tac
      have h_s2_val : (↑s2 : List U8) = List.slice 0 i8.val ↑pb_src := by
        rw [s2_post2, s1_post1]
      have h_s2_len' : (↑s2 : List U8).length = cb_encoded_vector.val := by
        rw [← Slice.length]; exact h_s2_len_eq
      have h_i8_val : i8.val = 0 + cb_encoded_vector.val := i8_post
      have h_cb_pb : 0 + cb_encoded_vector.val ≤ (↑pb_src : List U8).length := by
        have h_pas := h_pas_len
        have h_eq : pb_src.length = (↑pb_src : List U8).length := rfl
        rw [h_eq] at h_pas
        calc 0 + cb_encoded_vector.val
            = cb_encoded_vector.val := by ring
          _ ≤ (↑pb_src : List U8).length := h_pas
      have h_cb_enc : cb_encoded_vector.val ≤ (↑pk_mlkem_key.encoded_t : List U8).length := by
        rw [h_encoded_len]; exact h_cb_le
      have h_bridge := setSlice_eq_pb_byte (↑pk_mlkem_key.encoded_t) (↑s2) (↑pb_src)
              0 i8.val cb_encoded_vector.val
              h_s2_val h_s2_len' h_i8_val h_cb_pb h_cb_enc j h_j
      convert h_bridge using 2
      ring
  · intro t' enc' h_t'_len h_t'_wf
    -- Same as `ksv_decap_decode_t_prep.spec`: thread h_data straight through.
    have h_p5 := t_post5 t' enc' h_t'_len h_t'_wf
    obtain ⟨⟨h_wf, h_params, h_n_rows, h_hps, h_psd, h_prr⟩,
            h_encT, h_pubs, h_hash, h_hpk, h_data⟩ := h_p5
    exact ⟨h_wf, h_params, h_n_rows, h_encT, h_psd, h_prr,
           h_pubs, h_hash, h_hps, h_hpk, h_data⟩

end Symcrust.Properties.MLKEM
